In [1]:
import pandas as pd
from sklearn import model_selection
from sklearn.linear_model import LogisticRegression
from sklearn.externals import joblib
import pickle

In [2]:
url = "https://raw.githubusercontent.com/jbrownlee/Datasets/master/pima-indians-diabetes.data.csv"
names = ['preg', 'plas', 'pres', 'skin', 'test', 'mass', 'pedi', 'age', 'class']
dataframe = pandas.read_csv(url, names=names)
array = dataframe.values
X = array[:,0:8]
Y = array[:,8]
test_size = 0.33
seed = 7
X_train, X_test, Y_train, Y_test = model_selection.train_test_split(X, Y, test_size=test_size, random_state=seed)
# Fit the model on 33%
model = LogisticRegression()
model.fit(X_train, Y_train)
# save the model to disk
filename = 'mode_testing.sav'
joblib.dump(model, filename)

/anaconda3/lib/python3.6/site-packages/sklearn/linear_model/logistic.py:433: FutureWarning: Default solver will be changed to 'lbfgs' in 0.22. Specify a solver to silence this warning.
  FutureWarning)

['mode_testing.sav']

In [7]:
from sodapy import Socrata
client = Socrata("data.cityofnewyork.us", None)
result_tmp = []
for i in range(112235):
  results = client.get("t29m-gskq",where="passenger_count >= 1", offset=i)
  result_tmp = result_tmp + results

WARNING:root:Requests made without an app_token will be subject to strict throttling limits.

KeyboardInterrupt:

In [6]:
dataframe = pd.DataFrame.from_records(result_tmp)
dataframe.shape

(100000, 17)

In [8]:
df = pd.read_csv('yellow_tripdata_2018-01.csv')

In [36]:
df.shape

(8759874, 17)

In [133]:
time_pickup = df.iloc[50]["tpep_pickup_datetime"]
time_dropoff = df.iloc[50]["tpep_dropoff_datetime"]

In [134]:
import datetime
pickup_time = pd.Timestamp(time_pickup).isoformat()
dropoff_time = pd.Timestamp(time_dropoff).isoformat()
print(pickup_time)
print(dropoff_time)

2018-01-01T00:17:28
2018-01-01T00:37:38

In [135]:
#client1 = Socrata("data.cityofnewyork.us", "G13JC1xkBh10HyZbYdrlF350K", username="davidmao8419@gmail.com", password="Sz556622!")
client = Socrata("data.cityofnewyork.us", None)
query = "data_as_of between '"+pickup_time+"' and '"+dropoff_time+"'"
result = client.get("i4gi-tjb9",where=query)
#results = client.get("t29m-gskq",where="passenger_count >= 1", limit=1)

WARNING:root:Requests made without an app_token will be subject to strict throttling limits.

In [136]:
len(result)

540

In [141]:
id_map = {}
for i in range(len(result)):
    print(result[i]["data_as_of"]+" "+result[i]["borough"]+" "+result[i]["speed"]+" "+result[i]["link_id"])
    if(result[i]["link_id"] not in id_map):
        id_map[result[i]["link_id"]] = []
    id_map[result[i]["link_id"]].append(result[i]["data_as_of"])
    #print(result[i]["borough"])
    #print(result[i]["speed"])

2018-01-01T00:21:14.000 Queens 55.30 4362251
2018-01-01T00:21:14.000 Queens 60.27 4362247
2018-01-01T00:21:14.000 Queens 55.30 4362244
2018-01-01T00:22:10.000 Manhattan 39.76 4620343
2018-01-01T00:22:10.000 Manhattan 40.38 4329507
2018-01-01T00:22:10.000 Staten Island 51.57 4329483
2018-01-01T00:22:10.000 Manhattan 0.00 4329473
2018-01-01T00:22:10.000 Manhattan 0.00 4329472
2018-01-01T00:22:11.000 Brooklyn 44.73 4763657
2018-01-01T00:22:11.000 Brooklyn 54.05 4763656
2018-01-01T00:22:11.000 Brooklyn 45.36 4763655
2018-01-01T00:22:11.000 Brooklyn 55.92 4763652
2018-01-01T00:22:11.000 Brooklyn 53.43 4763651
2018-01-01T00:22:11.000 Staten Island 42.87 4763650
2018-01-01T00:22:11.000 Brooklyn 52.81 4763649
2018-01-01T00:22:11.000 Staten Island 45.36 4763648
2018-01-01T00:22:11.000 Manhattan 35.41 4456511
2018-01-01T00:22:11.000 Queens 32.31 4456510
2018-01-01T00:22:11.000 Manhattan 41.01 4456502
2018-01-01T00:22:11.000 Manhattan 9.94 4456501
2018-01-01T00:22:11.000 Queens 49.70 4456500
2018-01-01T00:22:11.000 Manhattan 16.15 4456494
2018-01-01T00:22:12.000 Queens 55.30 4616364
2018-01-01T00:22:12.000 Queens 32.93 4616357
2018-01-01T00:22:12.000 Queens 55.30 4616356
2018-01-01T00:22:12.000 Queens 56.54 4616355
2018-01-01T00:22:12.000 Queens 55.92 4616354
2018-01-01T00:22:12.000 Queens 27.34 4616353
2018-01-01T00:22:12.000 Queens 56.54 4616352
2018-01-01T00:22:12.000 Queens 57.78 4616351
2018-01-01T00:22:12.000 Queens 53.43 4616350
2018-01-01T00:22:12.000 Manhattan 46.60 4616346
2018-01-01T00:22:12.000 Manhattan 18.64 4616342
2018-01-01T00:22:12.000 Manhattan 25.47 4616341
2018-01-01T00:22:12.000 Manhattan 11.18 4616340
2018-01-01T00:22:12.000 Manhattan 36.66 4616339
2018-01-01T00:22:12.000 Manhattan 11.80 4616338
2018-01-01T00:22:12.000 Manhattan 19.26 4616337
2018-01-01T00:22:12.000 Manhattan 47.84 4616333
2018-01-01T00:22:12.000 Manhattan 44.73 4616332
2018-01-01T00:22:12.000 Manhattan 43.49 4616329
2018-01-01T00:22:12.000 Manhattan 46.60 4616328
2018-01-01T00:22:12.000 Manhattan 23.61 4616325
2018-01-01T00:22:12.000 Manhattan 18.64 4616324
2018-01-01T00:22:12.000 Manhattan 16.15 4616323
2018-01-01T00:22:12.000 Brooklyn 7.45 4616319
2018-01-01T00:22:12.000 Brooklyn 6.21 4616318
2018-01-01T00:22:12.000 Queens 54.05 4616312
2018-01-01T00:22:12.000 Queens 51.57 4616298
2018-01-01T00:22:12.000 Bronx 57.78 4616297
2018-01-01T00:22:12.000 Staten Island 52.81 4616281
2018-01-01T00:22:12.000 Queens 30.44 4616276
2018-01-01T00:22:12.000 Queens 55.92 4616272
2018-01-01T00:22:12.000 Bronx 57.78 4616267
2018-01-01T00:22:12.000 Bronx 0.00 4616266
2018-01-01T00:22:12.000 Queens 50.33 4616259
2018-01-01T00:22:12.000 Bronx 62.75 4616253
2018-01-01T00:22:12.000 Bronx 62.75 4616250
2018-01-01T00:22:12.000 Brooklyn 2.48 4616229
2018-01-01T00:22:12.000 Bronx 57.16 4616228
2018-01-01T00:22:12.000 Brooklyn 52.81 4616226
2018-01-01T00:22:12.000 Brooklyn 2.48 4616223
2018-01-01T00:22:12.000 Brooklyn 50.33 4616220
2018-01-01T00:22:12.000 Brooklyn 50.33 4616219
2018-01-01T00:22:12.000 Brooklyn 47.84 4616218
2018-01-01T00:22:12.000 Staten Island 52.81 4616215
2018-01-01T00:22:12.000 Staten Island 57.78 4616214
2018-01-01T00:22:12.000 Staten Island 57.78 4616213
2018-01-01T00:22:12.000 Staten Island 60.89 4616212
2018-01-01T00:22:12.000 Staten Island 58.40 4616211
2018-01-01T00:22:12.000 Staten Island 62.75 4616209
2018-01-01T00:22:12.000 Staten Island 50.33 4616208
2018-01-01T00:22:12.000 Staten Island 56.54 4616206
2018-01-01T00:22:12.000 Staten Island 42.25 4616205
2018-01-01T00:22:12.000 Staten island 42.25 4616204
2018-01-01T00:22:12.000 Staten Island 54.05 4616203
2018-01-01T00:22:12.000 Staten Island 63.37 4616202
2018-01-01T00:22:12.000 Staten Island 59.03 4616201
2018-01-01T00:22:12.000 Staten Island 52.81 4616200
2018-01-01T00:22:12.000 Staten Island 61.51 4616199
2018-01-01T00:22:12.000 Staten Island 58.40 4616198
2018-01-01T00:22:12.000 Staten Island 58.40 4616197
2018-01-01T00:22:12.000 Staten Island 58.40 4616195
2018-01-01T00:22:12.000 Staten Island 53.43 4616194
2018-01-01T00:22:12.000 Staten Island 57.16 4616193
2018-01-01T00:22:12.000 Staten Island 57.78 4616192
2018-01-01T00:22:12.000 Queens 54.68 4456506
2018-01-01T00:22:12.000 Queens 52.81 4456505
2018-01-01T00:22:12.000 Bronx 55.30 4456498
2018-01-01T00:22:12.000 Queens 51.57 4456497
2018-01-01T00:22:12.000 Bronx 54.68 4456496
2018-01-01T00:22:12.000 Queens 60.27 4456483
2018-01-01T00:22:12.000 Queens 0.00 4456481
2018-01-01T00:22:12.000 Queens 7.45 4456479
2018-01-01T00:22:12.000 Queens 3.10 4456478
2018-01-01T00:22:12.000 Queens 1.86 4456477
2018-01-01T00:22:12.000 Queens 9.94 4456476
2018-01-01T00:22:12.000 Manhattan 9.94 4456452
2018-01-01T00:22:12.000 Manhattan 40.38 4456450
2018-01-01T00:22:12.000 Queens 55.30 4362342
2018-01-01T00:22:12.000 Queens 57.16 4362250
2018-01-01T00:22:12.000 Queens 49.70 4362249
2018-01-01T00:22:14.000 Bronx 0.00 4620332
2018-01-01T00:22:14.000 Bronx 0.00 4620331
2018-01-01T00:22:14.000 Bronx 0.00 4620330
2018-01-01T00:22:14.000 Bronx 0.00 4620315
2018-01-01T00:22:14.000 Bronx 0.00 4620314
2018-01-01T00:22:14.000 Bronx 0.00 4620310
2018-01-01T00:22:14.000 Manhattan 0.00 4620298
2018-01-01T00:22:14.000 Queens 56.54 4362314
2018-01-01T00:22:14.000 Queens 68.97 4362252
2018-01-01T00:22:14.000 Manhattan 37.28 4329508
2018-01-01T00:22:14.000 Staten Island 0.00 4329499
2018-01-01T00:22:17.000 Queens 26.71 4616320
2018-01-01T00:22:17.000 Bronx 0.00 4616310
2018-01-01T00:22:17.000 Bronx 0.00 4616309
2018-01-01T00:22:17.000 Bronx 51.57 4616305
2018-01-01T00:22:17.000 Queens 54.68 4616300
2018-01-01T00:22:17.000 Queens 54.68 4616299
2018-01-01T00:22:17.000 Staten Island 0.00 4616282
2018-01-01T00:22:17.000 Bronx 57.16 4616261
2018-01-01T00:22:17.000 Bronx 57.16 4616260
2018-01-01T00:22:17.000 Bronx 14.91 4616255
2018-01-01T00:22:17.000 Bronx 57.78 4616252
2018-01-01T00:22:17.000 Bronx 57.78 4616247
2018-01-01T00:22:17.000 Bronx 57.78 4616246
2018-01-01T00:22:17.000 Queens 54.68 4616241
2018-01-01T00:22:17.000 Queens 54.68 4616239
2018-01-01T00:22:17.000 Brooklyn 0.00 4616235
2018-01-01T00:22:17.000 Brooklyn 0.00 4616232
2018-01-01T00:22:17.000 Queens 0.00 4616225
2018-01-01T00:22:17.000 Staten Island 0.00 4616217
2018-01-01T00:22:17.000 Staten Island 0.00 4616216
2018-01-01T00:22:17.000 Staten Island 0.00 4616210
2018-01-01T00:22:17.000 Staten Island 0.00 4616196
2018-01-01T00:27:10.000 Manhattan 41.63 4620343
2018-01-01T00:27:10.000 Manhattan 38.52 4329507
2018-01-01T00:27:10.000 Staten Island 52.19 4329483
2018-01-01T00:27:10.000 Manhattan 0.00 4329473
2018-01-01T00:27:10.000 Manhattan 0.00 4329472
2018-01-01T00:27:11.000 Brooklyn 45.36 4763657
2018-01-01T00:27:11.000 Brooklyn 54.68 4763656
2018-01-01T00:27:11.000 Brooklyn 45.36 4763655
2018-01-01T00:27:11.000 Brooklyn 57.16 4763652
2018-01-01T00:27:11.000 Brooklyn 52.81 4763651
2018-01-01T00:27:11.000 Staten Island 42.87 4763650
2018-01-01T00:27:11.000 Brooklyn 52.81 4763649
2018-01-01T00:27:11.000 Staten Island 45.98 4763648
2018-01-01T00:27:11.000 Manhattan 35.41 4456511
2018-01-01T00:27:11.000 Queens 32.31 4456510
2018-01-01T00:27:11.000 Queens 55.30 4456506
2018-01-01T00:27:11.000 Queens 52.81 4456505
2018-01-01T00:27:11.000 Manhattan 41.63 4456502
2018-01-01T00:27:11.000 Manhattan 5.59 4456501
2018-01-01T00:27:11.000 Queens 49.70 4456500
2018-01-01T00:27:11.000 Bronx 54.68 4456498
2018-01-01T00:27:11.000 Queens 52.19 4456497
2018-01-01T00:27:11.000 Bronx 54.05 4456496
2018-01-01T00:27:11.000 Manhattan 16.15 4456494
2018-01-01T00:27:11.000 Queens 59.65 4456483
2018-01-01T00:27:11.000 Queens 0.00 4456481
2018-01-01T00:27:11.000 Queens 9.94 4456479
2018-01-01T00:27:11.000 Queens 2.48 4456478
2018-01-01T00:27:11.000 Queens 3.10 4456477
2018-01-01T00:27:11.000 Queens 7.45 4456476
2018-01-01T00:27:11.000 Manhattan 7.45 4456452
2018-01-01T00:27:11.000 Manhattan 37.90 4456450
2018-01-01T00:27:11.000 Queens 54.68 4362342
2018-01-01T00:27:11.000 Queens 55.92 4362250
2018-01-01T00:27:11.000 Queens 50.33 4362249
2018-01-01T00:27:12.000 Bronx 0.00 4620332
2018-01-01T00:27:12.000 Bronx 0.00 4620331
2018-01-01T00:27:12.000 Bronx 0.00 4620330
2018-01-01T00:27:12.000 Bronx 0.00 4620315
2018-01-01T00:27:12.000 Bronx 0.00 4620314
2018-01-01T00:27:12.000 Bronx 0.00 4620310
2018-01-01T00:27:12.000 Manhattan 0.00 4620298
2018-01-01T00:27:12.000 Queens 54.68 4616364
2018-01-01T00:27:12.000 Queens 27.34 4616357
2018-01-01T00:27:12.000 Queens 54.05 4616356
2018-01-01T00:27:12.000 Queens 55.92 4616355
2018-01-01T00:27:12.000 Queens 55.92 4616354
2018-01-01T00:27:12.000 Queens 26.71 4616353
2018-01-01T00:27:12.000 Queens 56.54 4616352
2018-01-01T00:27:12.000 Queens 57.16 4616351
2018-01-01T00:27:12.000 Queens 57.16 4616350
2018-01-01T00:27:12.000 Manhattan 45.36 4616346
2018-01-01T00:27:12.000 Manhattan 19.26 4616342
2018-01-01T00:27:12.000 Manhattan 27.96 4616341
2018-01-01T00:27:12.000 Manhattan 8.07 4616340
2018-01-01T00:27:12.000 Manhattan 37.28 4616339
2018-01-01T00:27:12.000 Manhattan 11.80 4616338
2018-01-01T00:27:12.000 Manhattan 18.64 4616337
2018-01-01T00:27:12.000 Manhattan 44.11 4616333
2018-01-01T00:27:12.000 Manhattan 45.98 4616332
2018-01-01T00:27:12.000 Manhattan 41.63 4616329
2018-01-01T00:27:12.000 Manhattan 46.60 4616328
2018-01-01T00:27:12.000 Manhattan 22.99 4616325
2018-01-01T00:27:12.000 Manhattan 16.77 4616324
2018-01-01T00:27:12.000 Manhattan 15.53 4616323
2018-01-01T00:27:12.000 Brooklyn 6.83 4616319
2018-01-01T00:27:12.000 Brooklyn 7.45 4616318
2018-01-01T00:27:12.000 Queens 53.43 4616312
2018-01-01T00:27:12.000 Queens 50.95 4616298
2018-01-01T00:27:12.000 Bronx 55.30 4616297
2018-01-01T00:27:12.000 Staten Island 53.43 4616281
2018-01-01T00:27:12.000 Queens 39.14 4616276
2018-01-01T00:27:12.000 Queens 55.30 4616272
2018-01-01T00:27:12.000 Bronx 57.16 4616267
2018-01-01T00:27:12.000 Bronx 0.00 4616266
2018-01-01T00:27:12.000 Queens 51.57 4616259
2018-01-01T00:27:12.000 Bronx 62.13 4616253
2018-01-01T00:27:12.000 Bronx 62.75 4616250
2018-01-01T00:27:12.000 Brooklyn 2.48 4616229
2018-01-01T00:27:12.000 Bronx 57.78 4616228
2018-01-01T00:27:12.000 Brooklyn 52.19 4616226
2018-01-01T00:27:12.000 Brooklyn 2.48 4616223
2018-01-01T00:27:12.000 Brooklyn 50.33 4616220
2018-01-01T00:27:12.000 Brooklyn 47.84 4616219
2018-01-01T00:27:12.000 Brooklyn 47.84 4616218
2018-01-01T00:27:12.000 Staten Island 52.19 4616215
2018-01-01T00:27:12.000 Staten Island 55.30 4616214
2018-01-01T00:27:12.000 Staten Island 55.92 4616213
2018-01-01T00:27:12.000 Staten Island 59.03 4616212
2018-01-01T00:27:12.000 Staten Island 57.16 4616211
2018-01-01T00:27:12.000 Staten Island 63.37 4616209
2018-01-01T00:27:12.000 Staten Island 50.95 4616208
2018-01-01T00:27:12.000 Staten Island 56.54 4616206
2018-01-01T00:27:12.000 Staten Island 41.63 4616205
2018-01-01T00:27:12.000 Staten island 42.25 4616204
2018-01-01T00:27:12.000 Staten Island 55.30 4616203
2018-01-01T00:27:12.000 Staten Island 63.37 4616202
2018-01-01T00:27:12.000 Staten Island 59.03 4616201
2018-01-01T00:27:12.000 Staten Island 52.81 4616200
2018-01-01T00:27:12.000 Staten Island 60.27 4616199
2018-01-01T00:27:12.000 Staten Island 57.16 4616198
2018-01-01T00:27:12.000 Staten Island 57.78 4616197
2018-01-01T00:27:12.000 Staten Island 59.03 4616195
2018-01-01T00:27:12.000 Staten Island 54.05 4616194
2018-01-01T00:27:12.000 Staten Island 57.16 4616193
2018-01-01T00:27:12.000 Staten Island 57.16 4616192
2018-01-01T00:27:12.000 Manhattan 36.66 4329508
2018-01-01T00:27:12.000 Staten Island 0.00 4329499
2018-01-01T00:27:13.000 Queens 56.54 4362314
2018-01-01T00:27:13.000 Queens 52.19 4362252
2018-01-01T00:27:13.000 Queens 53.43 4362251
2018-01-01T00:27:13.000 Queens 59.65 4362247
2018-01-01T00:27:13.000 Queens 53.43 4362244
2018-01-01T00:27:17.000 Queens 29.20 4616320
2018-01-01T00:27:17.000 Bronx 0.00 4616310
2018-01-01T00:27:17.000 Bronx 0.00 4616309
2018-01-01T00:27:17.000 Bronx 52.19 4616305
2018-01-01T00:27:17.000 Queens 54.05 4616300
2018-01-01T00:27:17.000 Queens 54.05 4616299
2018-01-01T00:27:17.000 Staten Island 0.00 4616282
2018-01-01T00:27:17.000 Bronx 53.43 4616261
2018-01-01T00:27:17.000 Bronx 53.43 4616260
2018-01-01T00:27:17.000 Bronx 27.34 4616255
2018-01-01T00:27:17.000 Bronx 57.78 4616252
2018-01-01T00:27:17.000 Bronx 55.92 4616247
2018-01-01T00:27:17.000 Bronx 55.92 4616246
2018-01-01T00:27:17.000 Queens 54.68 4616241
2018-01-01T00:27:17.000 Queens 54.68 4616239
2018-01-01T00:27:17.000 Brooklyn 0.00 4616235
2018-01-01T00:27:17.000 Brooklyn 0.00 4616232
2018-01-01T00:27:17.000 Queens 0.00 4616225
2018-01-01T00:27:17.000 Staten Island 0.00 4616217
2018-01-01T00:27:17.000 Staten Island 0.00 4616216
2018-01-01T00:27:17.000 Staten Island 0.00 4616210
2018-01-01T00:27:17.000 Staten Island 0.00 4616196
2018-01-01T00:31:14.000 Queens 52.81 4362244
2018-01-01T00:32:10.000 Manhattan 46.60 4620343
2018-01-01T00:32:10.000 Manhattan 40.38 4329507
2018-01-01T00:32:10.000 Staten Island 51.57 4329483
2018-01-01T00:32:10.000 Manhattan 0.00 4329473
2018-01-01T00:32:10.000 Manhattan 0.00 4329472
2018-01-01T00:32:12.000 Brooklyn 44.73 4763657
2018-01-01T00:32:12.000 Brooklyn 54.05 4763656
2018-01-01T00:32:12.000 Brooklyn 44.73 4763655
2018-01-01T00:32:12.000 Brooklyn 56.54 4763652
2018-01-01T00:32:12.000 Brooklyn 53.43 4763651
2018-01-01T00:32:12.000 Staten Island 42.25 4763650
2018-01-01T00:32:12.000 Brooklyn 53.43 4763649
2018-01-01T00:32:12.000 Staten Island 45.98 4763648
2018-01-01T00:32:12.000 Manhattan 34.79 4456511
2018-01-01T00:32:12.000 Queens 37.90 4456510
2018-01-01T00:32:12.000 Queens 55.30 4456506
2018-01-01T00:32:12.000 Queens 52.81 4456505
2018-01-01T00:32:12.000 Manhattan 39.76 4456502
2018-01-01T00:32:12.000 Manhattan 36.03 4456501
2018-01-01T00:32:12.000 Queens 49.70 4456500
2018-01-01T00:32:12.000 Bronx 53.43 4456498
2018-01-01T00:32:12.000 Queens 52.81 4456497
2018-01-01T00:32:12.000 Bronx 52.19 4456496
2018-01-01T00:32:12.000 Manhattan 14.91 4456494
2018-01-01T00:32:12.000 Queens 52.81 4456483
2018-01-01T00:32:12.000 Queens 0.00 4456481
2018-01-01T00:32:12.000 Queens 32.31 4456479
2018-01-01T00:32:12.000 Queens 5.59 4456478
2018-01-01T00:32:12.000 Queens 11.18 4456477
2018-01-01T00:32:12.000 Queens 3.72 4456476
2018-01-01T00:32:12.000 Manhattan 3.72 4456452
2018-01-01T00:32:12.000 Manhattan 41.01 4456450
2018-01-01T00:32:12.000 Queens 53.43 4362342
2018-01-01T00:32:12.000 Queens 55.92 4362250
2018-01-01T00:32:12.000 Queens 50.33 4362249
2018-01-01T00:32:13.000 Bronx 0.00 4620332
2018-01-01T00:32:13.000 Bronx 0.00 4620331
2018-01-01T00:32:13.000 Bronx 0.00 4620330
2018-01-01T00:32:13.000 Bronx 0.00 4620315
2018-01-01T00:32:13.000 Bronx 0.00 4620314
2018-01-01T00:32:13.000 Bronx 0.00 4620310
2018-01-01T00:32:13.000 Manhattan 0.00 4620298
2018-01-01T00:32:13.000 Queens 56.54 4616364
2018-01-01T00:32:13.000 Queens 22.99 4616357
2018-01-01T00:32:13.000 Queens 54.05 4616356
2018-01-01T00:32:13.000 Queens 55.30 4616355
2018-01-01T00:32:13.000 Queens 56.54 4616354
2018-01-01T00:32:13.000 Queens 38.52 4616353
2018-01-01T00:32:13.000 Queens 55.30 4616352
2018-01-01T00:32:13.000 Queens 55.92 4616351
2018-01-01T00:32:13.000 Queens 57.78 4616350
2018-01-01T00:32:13.000 Manhattan 45.36 4616346
2018-01-01T00:32:13.000 Manhattan 18.01 4616342
2018-01-01T00:32:13.000 Manhattan 27.96 4616341
2018-01-01T00:32:13.000 Manhattan 6.21 4616340
2018-01-01T00:32:13.000 Manhattan 36.03 4616339
2018-01-01T00:32:13.000 Manhattan 10.56 4616338
2018-01-01T00:32:13.000 Manhattan 17.39 4616337
2018-01-01T00:32:13.000 Manhattan 47.22 4616333
2018-01-01T00:32:13.000 Manhattan 45.36 4616332
2018-01-01T00:32:13.000 Manhattan 37.28 4616329
2018-01-01T00:32:13.000 Manhattan 44.73 4616328
2018-01-01T00:32:13.000 Manhattan 22.36 4616325
2018-01-01T00:32:13.000 Manhattan 16.77 4616324
2018-01-01T00:32:13.000 Manhattan 12.42 4616323
2018-01-01T00:32:13.000 Brooklyn 6.83 4616319
2018-01-01T00:32:13.000 Brooklyn 0.00 4616318
2018-01-01T00:32:13.000 Queens 52.81 4616312
2018-01-01T00:32:13.000 Queens 49.08 4616298
2018-01-01T00:32:13.000 Bronx 55.30 4616297
2018-01-01T00:32:13.000 Staten Island 52.81 4616281
2018-01-01T00:32:13.000 Queens 44.11 4616276
2018-01-01T00:32:13.000 Queens 56.54 4616272
2018-01-01T00:32:13.000 Bronx 55.92 4616267
2018-01-01T00:32:13.000 Bronx 0.00 4616266
2018-01-01T00:32:13.000 Queens 50.95 4616259
2018-01-01T00:32:13.000 Bronx 59.03 4616253
2018-01-01T00:32:13.000 Bronx 63.37 4616250
2018-01-01T00:32:13.000 Brooklyn 2.48 4616229
2018-01-01T00:32:13.000 Bronx 59.65 4616228
2018-01-01T00:32:13.000 Brooklyn 50.95 4616226
2018-01-01T00:32:13.000 Brooklyn 2.48 4616223
2018-01-01T00:32:13.000 Brooklyn 49.70 4616220
2018-01-01T00:32:13.000 Brooklyn 49.08 4616219
2018-01-01T00:32:13.000 Brooklyn 47.22 4616218
2018-01-01T00:32:13.000 Staten Island 52.81 4616215
2018-01-01T00:32:13.000 Staten Island 56.54 4616214
2018-01-01T00:32:13.000 Staten Island 54.68 4616213
2018-01-01T00:32:13.000 Staten Island 56.54 4616212
2018-01-01T00:32:13.000 Staten Island 57.78 4616211
2018-01-01T00:32:13.000 Staten Island 63.37 4616209
2018-01-01T00:32:13.000 Staten Island 52.19 4616208
2018-01-01T00:32:13.000 Staten Island 57.16 4616206
2018-01-01T00:32:13.000 Staten Island 41.63 4616205
2018-01-01T00:32:13.000 Staten island 41.63 4616204
2018-01-01T00:32:13.000 Staten Island 55.30 4616203
2018-01-01T00:32:13.000 Staten Island 64.00 4616202
2018-01-01T00:32:13.000 Staten Island 60.89 4616201
2018-01-01T00:32:13.000 Staten Island 54.05 4616200
2018-01-01T00:32:13.000 Staten Island 61.51 4616199
2018-01-01T00:32:13.000 Staten Island 53.43 4616198
2018-01-01T00:32:13.000 Staten Island 54.05 4616197
2018-01-01T00:32:13.000 Staten Island 57.16 4616195
2018-01-01T00:32:13.000 Staten Island 53.43 4616194
2018-01-01T00:32:13.000 Staten Island 57.16 4616193
2018-01-01T00:32:13.000 Staten Island 56.54 4616192
2018-01-01T00:32:13.000 Manhattan 0.00 4329508
2018-01-01T00:32:13.000 Staten Island 0.00 4329499
2018-01-01T00:32:14.000 Queens 56.54 4362314
2018-01-01T00:32:14.000 Queens 52.81 4362252
2018-01-01T00:32:14.000 Queens 52.81 4362251
2018-01-01T00:32:14.000 Queens 55.30 4362247
2018-01-01T00:32:18.000 Queens 26.71 4616320
2018-01-01T00:32:18.000 Bronx 0.00 4616310
2018-01-01T00:32:18.000 Bronx 0.00 4616309
2018-01-01T00:32:18.000 Bronx 52.81 4616305
2018-01-01T00:32:18.000 Queens 54.68 4616300
2018-01-01T00:32:18.000 Queens 54.68 4616299
2018-01-01T00:32:18.000 Staten Island 0.00 4616282
2018-01-01T00:32:18.000 Bronx 41.63 4616261
2018-01-01T00:32:18.000 Bronx 41.63 4616260
2018-01-01T00:32:18.000 Bronx 14.91 4616255
2018-01-01T00:32:18.000 Bronx 57.78 4616252
2018-01-01T00:32:18.000 Bronx 57.16 4616247
2018-01-01T00:32:18.000 Bronx 57.16 4616246
2018-01-01T00:32:18.000 Queens 54.68 4616241
2018-01-01T00:32:18.000 Queens 54.68 4616239
2018-01-01T00:32:18.000 Brooklyn 0.00 4616235
2018-01-01T00:32:18.000 Brooklyn 0.00 4616232
2018-01-01T00:32:18.000 Queens 0.00 4616225
2018-01-01T00:32:18.000 Staten Island 0.00 4616217
2018-01-01T00:32:18.000 Staten Island 0.00 4616216
2018-01-01T00:32:18.000 Staten Island 0.00 4616210
2018-01-01T00:32:18.000 Staten Island 0.00 4616196
2018-01-01T00:36:13.000 Queens 52.81 4362244
2018-01-01T00:37:09.000 Manhattan 41.63 4620343
2018-01-01T00:37:09.000 Manhattan 34.17 4329507
2018-01-01T00:37:09.000 Staten Island 48.46 4329483
2018-01-01T00:37:09.000 Manhattan 0.00 4329473
2018-01-01T00:37:09.000 Manhattan 0.00 4329472
2018-01-01T00:37:11.000 Brooklyn 44.11 4763657
2018-01-01T00:37:11.000 Brooklyn 54.05 4763656
2018-01-01T00:37:11.000 Brooklyn 44.73 4763655
2018-01-01T00:37:11.000 Brooklyn 54.05 4763652
2018-01-01T00:37:11.000 Brooklyn 52.81 4763651
2018-01-01T00:37:11.000 Staten Island 42.25 4763650
2018-01-01T00:37:11.000 Brooklyn 54.68 4763649
2018-01-01T00:37:11.000 Staten Island 45.98 4763648
2018-01-01T00:37:11.000 Manhattan 36.03 4456511
2018-01-01T00:37:11.000 Queens 37.90 4456510
2018-01-01T00:37:11.000 Manhattan 41.01 4456502
2018-01-01T00:37:11.000 Manhattan 37.28 4456501
2018-01-01T00:37:11.000 Queens 48.46 4456500
2018-01-01T00:37:11.000 Manhattan 14.29 4456494

In [142]:
id_map
#results1 = client.get("p8np-it66", where="Date = '2018-05-20T00:00:00.000'")

{'4329472': ['2018-01-01T00:22:10.000',
  '2018-01-01T00:27:10.000',
  '2018-01-01T00:32:10.000',
  '2018-01-01T00:37:09.000'],
 '4329473': ['2018-01-01T00:22:10.000',
  '2018-01-01T00:27:10.000',
  '2018-01-01T00:32:10.000',
  '2018-01-01T00:37:09.000'],
 '4329483': ['2018-01-01T00:22:10.000',
  '2018-01-01T00:27:10.000',
  '2018-01-01T00:32:10.000',
  '2018-01-01T00:37:09.000'],
 '4329499': ['2018-01-01T00:22:14.000',
  '2018-01-01T00:27:12.000',
  '2018-01-01T00:32:13.000',
  '2018-01-01T00:37:13.000'],
 '4329507': ['2018-01-01T00:22:10.000',
  '2018-01-01T00:27:10.000',
  '2018-01-01T00:32:10.000',
  '2018-01-01T00:37:09.000'],
 '4329508': ['2018-01-01T00:22:14.000',
  '2018-01-01T00:27:12.000',
  '2018-01-01T00:32:13.000',
  '2018-01-01T00:37:13.000'],
 '4362244': ['2018-01-01T00:21:14.000',
  '2018-01-01T00:27:13.000',
  '2018-01-01T00:31:14.000',
  '2018-01-01T00:36:13.000'],
 '4362247': ['2018-01-01T00:21:14.000',
  '2018-01-01T00:27:13.000',
  '2018-01-01T00:32:14.000',
  '2018-01-01T00:37:14.000'],
 '4362249': ['2018-01-01T00:22:12.000',
  '2018-01-01T00:27:11.000',
  '2018-01-01T00:32:12.000',
  '2018-01-01T00:37:12.000'],
 '4362250': ['2018-01-01T00:22:12.000',
  '2018-01-01T00:27:11.000',
  '2018-01-01T00:32:12.000',
  '2018-01-01T00:37:12.000'],
 '4362251': ['2018-01-01T00:21:14.000',
  '2018-01-01T00:27:13.000',
  '2018-01-01T00:32:14.000',
  '2018-01-01T00:37:14.000'],
 '4362252': ['2018-01-01T00:22:14.000',
  '2018-01-01T00:27:13.000',
  '2018-01-01T00:32:14.000',
  '2018-01-01T00:37:14.000'],
 '4362314': ['2018-01-01T00:22:14.000',
  '2018-01-01T00:27:13.000',
  '2018-01-01T00:32:14.000',
  '2018-01-01T00:37:14.000'],
 '4362342': ['2018-01-01T00:22:12.000',
  '2018-01-01T00:27:11.000',
  '2018-01-01T00:32:12.000',
  '2018-01-01T00:37:12.000'],
 '4456450': ['2018-01-01T00:22:12.000',
  '2018-01-01T00:27:11.000',
  '2018-01-01T00:32:12.000',
  '2018-01-01T00:37:12.000'],
 '4456452': ['2018-01-01T00:22:12.000',
  '2018-01-01T00:27:11.000',
  '2018-01-01T00:32:12.000',
  '2018-01-01T00:37:12.000'],
 '4456476': ['2018-01-01T00:22:12.000',
  '2018-01-01T00:27:11.000',
  '2018-01-01T00:32:12.000',
  '2018-01-01T00:37:12.000'],
 '4456477': ['2018-01-01T00:22:12.000',
  '2018-01-01T00:27:11.000',
  '2018-01-01T00:32:12.000',
  '2018-01-01T00:37:12.000'],
 '4456478': ['2018-01-01T00:22:12.000',
  '2018-01-01T00:27:11.000',
  '2018-01-01T00:32:12.000',
  '2018-01-01T00:37:12.000'],
 '4456479': ['2018-01-01T00:22:12.000',
  '2018-01-01T00:27:11.000',
  '2018-01-01T00:32:12.000',
  '2018-01-01T00:37:12.000'],
 '4456481': ['2018-01-01T00:22:12.000',
  '2018-01-01T00:27:11.000',
  '2018-01-01T00:32:12.000',
  '2018-01-01T00:37:12.000'],
 '4456483': ['2018-01-01T00:22:12.000',
  '2018-01-01T00:27:11.000',
  '2018-01-01T00:32:12.000',
  '2018-01-01T00:37:12.000'],
 '4456494': ['2018-01-01T00:22:11.000',
  '2018-01-01T00:27:11.000',
  '2018-01-01T00:32:12.000',
  '2018-01-01T00:37:11.000'],
 '4456496': ['2018-01-01T00:22:12.000',
  '2018-01-01T00:27:11.000',
  '2018-01-01T00:32:12.000',
  '2018-01-01T00:37:12.000'],
 '4456497': ['2018-01-01T00:22:12.000',
  '2018-01-01T00:27:11.000',
  '2018-01-01T00:32:12.000',
  '2018-01-01T00:37:12.000'],
 '4456498': ['2018-01-01T00:22:12.000',
  '2018-01-01T00:27:11.000',
  '2018-01-01T00:32:12.000',
  '2018-01-01T00:37:12.000'],
 '4456500': ['2018-01-01T00:22:11.000',
  '2018-01-01T00:27:11.000',
  '2018-01-01T00:32:12.000',
  '2018-01-01T00:37:11.000'],
 '4456501': ['2018-01-01T00:22:11.000',
  '2018-01-01T00:27:11.000',
  '2018-01-01T00:32:12.000',
  '2018-01-01T00:37:11.000'],
 '4456502': ['2018-01-01T00:22:11.000',
  '2018-01-01T00:27:11.000',
  '2018-01-01T00:32:12.000',
  '2018-01-01T00:37:11.000'],
 '4456505': ['2018-01-01T00:22:12.000',
  '2018-01-01T00:27:11.000',
  '2018-01-01T00:32:12.000',
  '2018-01-01T00:37:12.000'],
 '4456506': ['2018-01-01T00:22:12.000',
  '2018-01-01T00:27:11.000',
  '2018-01-01T00:32:12.000',
  '2018-01-01T00:37:12.000'],
 '4456510': ['2018-01-01T00:22:11.000',
  '2018-01-01T00:27:11.000',
  '2018-01-01T00:32:12.000',
  '2018-01-01T00:37:11.000'],
 '4456511': ['2018-01-01T00:22:11.000',
  '2018-01-01T00:27:11.000',
  '2018-01-01T00:32:12.000',
  '2018-01-01T00:37:11.000'],
 '4616192': ['2018-01-01T00:22:12.000',
  '2018-01-01T00:27:12.000',
  '2018-01-01T00:32:13.000',
  '2018-01-01T00:37:15.000'],
 '4616193': ['2018-01-01T00:22:12.000',
  '2018-01-01T00:27:12.000',
  '2018-01-01T00:32:13.000',
  '2018-01-01T00:37:15.000'],
 '4616194': ['2018-01-01T00:22:12.000',
  '2018-01-01T00:27:12.000',
  '2018-01-01T00:32:13.000',
  '2018-01-01T00:37:15.000'],
 '4616195': ['2018-01-01T00:22:12.000',
  '2018-01-01T00:27:12.000',
  '2018-01-01T00:32:13.000',
  '2018-01-01T00:37:15.000'],
 '4616196': ['2018-01-01T00:22:17.000',
  '2018-01-01T00:27:17.000',
  '2018-01-01T00:32:18.000',
  '2018-01-01T00:37:20.000'],
 '4616197': ['2018-01-01T00:22:12.000',
  '2018-01-01T00:27:12.000',
  '2018-01-01T00:32:13.000',
  '2018-01-01T00:37:15.000'],
 '4616198': ['2018-01-01T00:22:12.000',
  '2018-01-01T00:27:12.000',
  '2018-01-01T00:32:13.000',
  '2018-01-01T00:37:15.000'],
 '4616199': ['2018-01-01T00:22:12.000',
  '2018-01-01T00:27:12.000',
  '2018-01-01T00:32:13.000',
  '2018-01-01T00:37:15.000'],
 '4616200': ['2018-01-01T00:22:12.000',
  '2018-01-01T00:27:12.000',
  '2018-01-01T00:32:13.000',
  '2018-01-01T00:37:15.000'],
 '4616201': ['2018-01-01T00:22:12.000',
  '2018-01-01T00:27:12.000',
  '2018-01-01T00:32:13.000',
  '2018-01-01T00:37:15.000'],
 '4616202': ['2018-01-01T00:22:12.000',
  '2018-01-01T00:27:12.000',
  '2018-01-01T00:32:13.000',
  '2018-01-01T00:37:15.000'],
 '4616203': ['2018-01-01T00:22:12.000',
  '2018-01-01T00:27:12.000',
  '2018-01-01T00:32:13.000',
  '2018-01-01T00:37:15.000'],
 '4616204': ['2018-01-01T00:22:12.000',
  '2018-01-01T00:27:12.000',
  '2018-01-01T00:32:13.000',
  '2018-01-01T00:37:15.000'],
 '4616205': ['2018-01-01T00:22:12.000',
  '2018-01-01T00:27:12.000',
  '2018-01-01T00:32:13.000',
  '2018-01-01T00:37:15.000'],
 '4616206': ['2018-01-01T00:22:12.000',
  '2018-01-01T00:27:12.000',
  '2018-01-01T00:32:13.000',
  '2018-01-01T00:37:15.000'],
 '4616208': ['2018-01-01T00:22:12.000',
  '2018-01-01T00:27:12.000',
  '2018-01-01T00:32:13.000',
  '2018-01-01T00:37:15.000'],
 '4616209': ['2018-01-01T00:22:12.000',
  '2018-01-01T00:27:12.000',
  '2018-01-01T00:32:13.000',
  '2018-01-01T00:37:15.000'],
 '4616210': ['2018-01-01T00:22:17.000',
  '2018-01-01T00:27:17.000',
  '2018-01-01T00:32:18.000',
  '2018-01-01T00:37:20.000'],
 '4616211': ['2018-01-01T00:22:12.000',
  '2018-01-01T00:27:12.000',
  '2018-01-01T00:32:13.000',
  '2018-01-01T00:37:15.000'],
 '4616212': ['2018-01-01T00:22:12.000',
  '2018-01-01T00:27:12.000',
  '2018-01-01T00:32:13.000',
  '2018-01-01T00:37:15.000'],
 '4616213': ['2018-01-01T00:22:12.000',
  '2018-01-01T00:27:12.000',
  '2018-01-01T00:32:13.000',
  '2018-01-01T00:37:15.000'],
 '4616214': ['2018-01-01T00:22:12.000',
  '2018-01-01T00:27:12.000',
  '2018-01-01T00:32:13.000',
  '2018-01-01T00:37:15.000'],
 '4616215': ['2018-01-01T00:22:12.000',
  '2018-01-01T00:27:12.000',
  '2018-01-01T00:32:13.000',
  '2018-01-01T00:37:15.000'],
 '4616216': ['2018-01-01T00:22:17.000',
  '2018-01-01T00:27:17.000',
  '2018-01-01T00:32:18.000',
  '2018-01-01T00:37:20.000'],
 '4616217': ['2018-01-01T00:22:17.000',
  '2018-01-01T00:27:17.000',
  '2018-01-01T00:32:18.000',
  '2018-01-01T00:37:20.000'],
 '4616218': ['2018-01-01T00:22:12.000',
  '2018-01-01T00:27:12.000',
  '2018-01-01T00:32:13.000',
  '2018-01-01T00:37:15.000'],
 '4616219': ['2018-01-01T00:22:12.000',
  '2018-01-01T00:27:12.000',
  '2018-01-01T00:32:13.000',
  '2018-01-01T00:37:15.000'],
 '4616220': ['2018-01-01T00:22:12.000',
  '2018-01-01T00:27:12.000',
  '2018-01-01T00:32:13.000',
  '2018-01-01T00:37:15.000'],
 '4616223': ['2018-01-01T00:22:12.000',
  '2018-01-01T00:27:12.000',
  '2018-01-01T00:32:13.000',
  '2018-01-01T00:37:15.000'],
 '4616225': ['2018-01-01T00:22:17.000',
  '2018-01-01T00:27:17.000',
  '2018-01-01T00:32:18.000',
  '2018-01-01T00:37:20.000'],
 '4616226': ['2018-01-01T00:22:12.000',
  '2018-01-01T00:27:12.000',
  '2018-01-01T00:32:13.000',
  '2018-01-01T00:37:15.000'],
 '4616228': ['2018-01-01T00:22:12.000',
  '2018-01-01T00:27:12.000',
  '2018-01-01T00:32:13.000',
  '2018-01-01T00:37:15.000'],
 '4616229': ['2018-01-01T00:22:12.000',
  '2018-01-01T00:27:12.000',
  '2018-01-01T00:32:13.000',
  '2018-01-01T00:37:15.000'],
 '4616232': ['2018-01-01T00:22:17.000',
  '2018-01-01T00:27:17.000',
  '2018-01-01T00:32:18.000',
  '2018-01-01T00:37:20.000'],
 '4616235': ['2018-01-01T00:22:17.000',
  '2018-01-01T00:27:17.000',
  '2018-01-01T00:32:18.000',
  '2018-01-01T00:37:20.000'],
 '4616239': ['2018-01-01T00:22:17.000',
  '2018-01-01T00:27:17.000',
  '2018-01-01T00:32:18.000',
  '2018-01-01T00:37:20.000'],
 '4616241': ['2018-01-01T00:22:17.000',
  '2018-01-01T00:27:17.000',
  '2018-01-01T00:32:18.000',
  '2018-01-01T00:37:20.000'],
 '4616246': ['2018-01-01T00:22:17.000',
  '2018-01-01T00:27:17.000',
  '2018-01-01T00:32:18.000',
  '2018-01-01T00:37:20.000'],
 '4616247': ['2018-01-01T00:22:17.000',
  '2018-01-01T00:27:17.000',
  '2018-01-01T00:32:18.000',
  '2018-01-01T00:37:20.000'],
 '4616250': ['2018-01-01T00:22:12.000',
  '2018-01-01T00:27:12.000',
  '2018-01-01T00:32:13.000',
  '2018-01-01T00:37:15.000'],
 '4616252': ['2018-01-01T00:22:17.000',
  '2018-01-01T00:27:17.000',
  '2018-01-01T00:32:18.000',
  '2018-01-01T00:37:20.000'],
 '4616253': ['2018-01-01T00:22:12.000',
  '2018-01-01T00:27:12.000',
  '2018-01-01T00:32:13.000',
  '2018-01-01T00:37:15.000'],
 '4616255': ['2018-01-01T00:22:17.000',
  '2018-01-01T00:27:17.000',
  '2018-01-01T00:32:18.000',
  '2018-01-01T00:37:20.000'],
 '4616259': ['2018-01-01T00:22:12.000',
  '2018-01-01T00:27:12.000',
  '2018-01-01T00:32:13.000',
  '2018-01-01T00:37:15.000'],
 '4616260': ['2018-01-01T00:22:17.000',
  '2018-01-01T00:27:17.000',
  '2018-01-01T00:32:18.000',
  '2018-01-01T00:37:20.000'],
 '4616261': ['2018-01-01T00:22:17.000',
  '2018-01-01T00:27:17.000',
  '2018-01-01T00:32:18.000',
  '2018-01-01T00:37:20.000'],
 '4616266': ['2018-01-01T00:22:12.000',
  '2018-01-01T00:27:12.000',
  '2018-01-01T00:32:13.000',
  '2018-01-01T00:37:15.000'],
 '4616267': ['2018-01-01T00:22:12.000',
  '2018-01-01T00:27:12.000',
  '2018-01-01T00:32:13.000',
  '2018-01-01T00:37:15.000'],
 '4616272': ['2018-01-01T00:22:12.000',
  '2018-01-01T00:27:12.000',
  '2018-01-01T00:32:13.000',
  '2018-01-01T00:37:15.000'],
 '4616276': ['2018-01-01T00:22:12.000',
  '2018-01-01T00:27:12.000',
  '2018-01-01T00:32:13.000',
  '2018-01-01T00:37:15.000'],
 '4616281': ['2018-01-01T00:22:12.000',
  '2018-01-01T00:27:12.000',
  '2018-01-01T00:32:13.000',
  '2018-01-01T00:37:15.000'],
 '4616282': ['2018-01-01T00:22:17.000',
  '2018-01-01T00:27:17.000',
  '2018-01-01T00:32:18.000',
  '2018-01-01T00:37:20.000'],
 '4616297': ['2018-01-01T00:22:12.000',
  '2018-01-01T00:27:12.000',
  '2018-01-01T00:32:13.000',
  '2018-01-01T00:37:15.000'],
 '4616298': ['2018-01-01T00:22:12.000',
  '2018-01-01T00:27:12.000',
  '2018-01-01T00:32:13.000',
  '2018-01-01T00:37:15.000'],
 '4616299': ['2018-01-01T00:22:17.000',
  '2018-01-01T00:27:17.000',
  '2018-01-01T00:32:18.000',
  '2018-01-01T00:37:20.000'],
 '4616300': ['2018-01-01T00:22:17.000',
  '2018-01-01T00:27:17.000',
  '2018-01-01T00:32:18.000',
  '2018-01-01T00:37:20.000'],
 '4616305': ['2018-01-01T00:22:17.000',
  '2018-01-01T00:27:17.000',
  '2018-01-01T00:32:18.000',
  '2018-01-01T00:37:20.000'],
 '4616309': ['2018-01-01T00:22:17.000',
  '2018-01-01T00:27:17.000',
  '2018-01-01T00:32:18.000',
  '2018-01-01T00:37:20.000'],
 '4616310': ['2018-01-01T00:22:17.000',
  '2018-01-01T00:27:17.000',
  '2018-01-01T00:32:18.000',
  '2018-01-01T00:37:20.000'],
 '4616312': ['2018-01-01T00:22:12.000',
  '2018-01-01T00:27:12.000',
  '2018-01-01T00:32:13.000',
  '2018-01-01T00:37:15.000'],
 '4616318': ['2018-01-01T00:22:12.000',
  '2018-01-01T00:27:12.000',
  '2018-01-01T00:32:13.000',
  '2018-01-01T00:37:15.000'],
 '4616319': ['2018-01-01T00:22:12.000',
  '2018-01-01T00:27:12.000',
  '2018-01-01T00:32:13.000',
  '2018-01-01T00:37:15.000'],
 '4616320': ['2018-01-01T00:22:17.000',
  '2018-01-01T00:27:17.000',
  '2018-01-01T00:32:18.000',
  '2018-01-01T00:37:20.000'],
 '4616323': ['2018-01-01T00:22:12.000',
  '2018-01-01T00:27:12.000',
  '2018-01-01T00:32:13.000',
  '2018-01-01T00:37:15.000'],
 '4616324': ['2018-01-01T00:22:12.000',
  '2018-01-01T00:27:12.000',
  '2018-01-01T00:32:13.000',
  '2018-01-01T00:37:15.000'],
 '4616325': ['2018-01-01T00:22:12.000',
  '2018-01-01T00:27:12.000',
  '2018-01-01T00:32:13.000',
  '2018-01-01T00:37:15.000'],
 '4616328': ['2018-01-01T00:22:12.000',
  '2018-01-01T00:27:12.000',
  '2018-01-01T00:32:13.000',
  '2018-01-01T00:37:15.000'],
 '4616329': ['2018-01-01T00:22:12.000',
  '2018-01-01T00:27:12.000',
  '2018-01-01T00:32:13.000',
  '2018-01-01T00:37:15.000'],
 '4616332': ['2018-01-01T00:22:12.000',
  '2018-01-01T00:27:12.000',
  '2018-01-01T00:32:13.000',
  '2018-01-01T00:37:15.000'],
 '4616333': ['2018-01-01T00:22:12.000',
  '2018-01-01T00:27:12.000',
  '2018-01-01T00:32:13.000',
  '2018-01-01T00:37:15.000'],
 '4616337': ['2018-01-01T00:22:12.000',
  '2018-01-01T00:27:12.000',
  '2018-01-01T00:32:13.000',
  '2018-01-01T00:37:15.000'],
 '4616338': ['2018-01-01T00:22:12.000',
  '2018-01-01T00:27:12.000',
  '2018-01-01T00:32:13.000',
  '2018-01-01T00:37:15.000'],
 '4616339': ['2018-01-01T00:22:12.000',
  '2018-01-01T00:27:12.000',
  '2018-01-01T00:32:13.000',
  '2018-01-01T00:37:15.000'],
 '4616340': ['2018-01-01T00:22:12.000',
  '2018-01-01T00:27:12.000',
  '2018-01-01T00:32:13.000',
  '2018-01-01T00:37:15.000'],
 '4616341': ['2018-01-01T00:22:12.000',
  '2018-01-01T00:27:12.000',
  '2018-01-01T00:32:13.000',
  '2018-01-01T00:37:15.000'],
 '4616342': ['2018-01-01T00:22:12.000',
  '2018-01-01T00:27:12.000',
  '2018-01-01T00:32:13.000',
  '2018-01-01T00:37:15.000'],
 '4616346': ['2018-01-01T00:22:12.000',
  '2018-01-01T00:27:12.000',
  '2018-01-01T00:32:13.000',
  '2018-01-01T00:37:15.000'],
 '4616350': ['2018-01-01T00:22:12.000',
  '2018-01-01T00:27:12.000',
  '2018-01-01T00:32:13.000',
  '2018-01-01T00:37:15.000'],
 '4616351': ['2018-01-01T00:22:12.000',
  '2018-01-01T00:27:12.000',
  '2018-01-01T00:32:13.000',
  '2018-01-01T00:37:15.000'],
 '4616352': ['2018-01-01T00:22:12.000',
  '2018-01-01T00:27:12.000',
  '2018-01-01T00:32:13.000',
  '2018-01-01T00:37:15.000'],
 '4616353': ['2018-01-01T00:22:12.000',
  '2018-01-01T00:27:12.000',
  '2018-01-01T00:32:13.000',
  '2018-01-01T00:37:15.000'],
 '4616354': ['2018-01-01T00:22:12.000',
  '2018-01-01T00:27:12.000',
  '2018-01-01T00:32:13.000',
  '2018-01-01T00:37:15.000'],
 '4616355': ['2018-01-01T00:22:12.000',
  '2018-01-01T00:27:12.000',
  '2018-01-01T00:32:13.000',
  '2018-01-01T00:37:15.000'],
 '4616356': ['2018-01-01T00:22:12.000',
  '2018-01-01T00:27:12.000',
  '2018-01-01T00:32:13.000',
  '2018-01-01T00:37:15.000'],
 '4616357': ['2018-01-01T00:22:12.000',
  '2018-01-01T00:27:12.000',
  '2018-01-01T00:32:13.000',
  '2018-01-01T00:37:15.000'],
 '4616364': ['2018-01-01T00:22:12.000',
  '2018-01-01T00:27:12.000',
  '2018-01-01T00:32:13.000',
  '2018-01-01T00:37:15.000'],
 '4620298': ['2018-01-01T00:22:14.000',
  '2018-01-01T00:27:12.000',
  '2018-01-01T00:32:13.000',
  '2018-01-01T00:37:13.000'],
 '4620310': ['2018-01-01T00:22:14.000',
  '2018-01-01T00:27:12.000',
  '2018-01-01T00:32:13.000',
  '2018-01-01T00:37:13.000'],
 '4620314': ['2018-01-01T00:22:14.000',
  '2018-01-01T00:27:12.000',
  '2018-01-01T00:32:13.000',
  '2018-01-01T00:37:13.000'],
 '4620315': ['2018-01-01T00:22:14.000',
  '2018-01-01T00:27:12.000',
  '2018-01-01T00:32:13.000',
  '2018-01-01T00:37:13.000'],
 '4620330': ['2018-01-01T00:22:14.000',
  '2018-01-01T00:27:12.000',
  '2018-01-01T00:32:13.000',
  '2018-01-01T00:37:13.000'],
 '4620331': ['2018-01-01T00:22:14.000',
  '2018-01-01T00:27:12.000',
  '2018-01-01T00:32:13.000',
  '2018-01-01T00:37:13.000'],
 '4620332': ['2018-01-01T00:22:14.000',
  '2018-01-01T00:27:12.000',
  '2018-01-01T00:32:13.000',
  '2018-01-01T00:37:13.000'],
 '4620343': ['2018-01-01T00:22:10.000',
  '2018-01-01T00:27:10.000',
  '2018-01-01T00:32:10.000',
  '2018-01-01T00:37:09.000'],
 '4763648': ['2018-01-01T00:22:11.000',
  '2018-01-01T00:27:11.000',
  '2018-01-01T00:32:12.000',
  '2018-01-01T00:37:11.000'],
 '4763649': ['2018-01-01T00:22:11.000',
  '2018-01-01T00:27:11.000',
  '2018-01-01T00:32:12.000',
  '2018-01-01T00:37:11.000'],
 '4763650': ['2018-01-01T00:22:11.000',
  '2018-01-01T00:27:11.000',
  '2018-01-01T00:32:12.000',
  '2018-01-01T00:37:11.000'],
 '4763651': ['2018-01-01T00:22:11.000',
  '2018-01-01T00:27:11.000',
  '2018-01-01T00:32:12.000',
  '2018-01-01T00:37:11.000'],
 '4763652': ['2018-01-01T00:22:11.000',
  '2018-01-01T00:27:11.000',
  '2018-01-01T00:32:12.000',
  '2018-01-01T00:37:11.000'],
 '4763655': ['2018-01-01T00:22:11.000',
  '2018-01-01T00:27:11.000',
  '2018-01-01T00:32:12.000',
  '2018-01-01T00:37:11.000'],
 '4763656': ['2018-01-01T00:22:11.000',
  '2018-01-01T00:27:11.000',
  '2018-01-01T00:32:12.000',
  '2018-01-01T00:37:11.000'],
 '4763657': ['2018-01-01T00:22:11.000',
  '2018-01-01T00:27:11.000',
  '2018-01-01T00:32:12.000',
  '2018-01-01T00:37:11.000']}

In [143]:
con_df = pd.read_csv('Street_Closures_due_to_construction_activities_by_Block.csv')

In [186]:
def daterange(start_date, end_date):
    for n in range(int ((end_date - start_date).days) +1):
        yield start_date + datetime.timedelta(n)

check=0
date_construction_num = {}

for index, row in con_df.iterrows():
    #if(check==5):
    #    break

    start_date = pd.Timestamp(row["WORK_START_DATE"])
    end_date = pd.Timestamp(row["WORK_END_DATE"])

    for n in range(int ((end_date - start_date).days) +1):
        #print((start_date+datetime.timedelta(n)).date())
        date = (start_date+datetime.timedelta(n)).date()
        if(date not in date_construction_num):
            date_construction_num[date] = {'M':0, 'X':0, 'B':0, 'Q':0, 'S':0}
        
        date_construction_num[date][row["BOROUGH_CODE"]] =  date_construction_num[date][row["BOROUGH_CODE"]] + 1
    
    check = check + 1

In [187]:
date_construction_num

{datetime.date(2017, 2, 2): {'B': 0, 'M': 10, 'Q': 0, 'S': 0, 'X': 0},
 datetime.date(2017, 2, 3): {'B': 1, 'M': 10, 'Q': 0, 'S': 0, 'X': 0},
 datetime.date(2017, 2, 4): {'B': 1, 'M': 10, 'Q': 0, 'S': 0, 'X': 0},
 datetime.date(2017, 2, 5): {'B': 1, 'M': 10, 'Q': 0, 'S': 0, 'X': 0},
 datetime.date(2017, 2, 6): {'B': 1, 'M': 10, 'Q': 0, 'S': 0, 'X': 0},
 datetime.date(2017, 2, 7): {'B': 1, 'M': 10, 'Q': 0, 'S': 0, 'X': 0},
 datetime.date(2017, 2, 8): {'B': 1, 'M': 10, 'Q': 0, 'S': 0, 'X': 0},
 datetime.date(2017, 2, 9): {'B': 1, 'M': 10, 'Q': 0, 'S': 0, 'X': 0},
 datetime.date(2017, 2, 10): {'B': 1, 'M': 10, 'Q': 0, 'S': 0, 'X': 0},
 datetime.date(2017, 2, 11): {'B': 1, 'M': 10, 'Q': 0, 'S': 0, 'X': 0},
 datetime.date(2017, 2, 12): {'B': 1, 'M': 10, 'Q': 0, 'S': 0, 'X': 0},
 datetime.date(2017, 2, 13): {'B': 1, 'M': 10, 'Q': 0, 'S': 0, 'X': 0},
 datetime.date(2017, 2, 14): {'B': 1, 'M': 10, 'Q': 0, 'S': 0, 'X': 0},
 datetime.date(2017, 2, 15): {'B': 1, 'M': 10, 'Q': 0, 'S': 0, 'X': 0},
 datetime.date(2017, 2, 16): {'B': 1, 'M': 12, 'Q': 0, 'S': 0, 'X': 0},
 datetime.date(2017, 2, 17): {'B': 1, 'M': 14, 'Q': 0, 'S': 0, 'X': 0},
 datetime.date(2017, 2, 18): {'B': 1, 'M': 14, 'Q': 0, 'S': 0, 'X': 0},
 datetime.date(2017, 2, 19): {'B': 1, 'M': 14, 'Q': 0, 'S': 0, 'X': 0},
 datetime.date(2017, 2, 20): {'B': 1, 'M': 14, 'Q': 0, 'S': 0, 'X': 0},
 datetime.date(2017, 2, 21): {'B': 1, 'M': 14, 'Q': 2, 'S': 0, 'X': 0},
 datetime.date(2017, 2, 22): {'B': 1, 'M': 15, 'Q': 2, 'S': 0, 'X': 0},
 datetime.date(2017, 2, 23): {'B': 1, 'M': 15, 'Q': 2, 'S': 0, 'X': 2},
 datetime.date(2017, 2, 24): {'B': 1, 'M': 16, 'Q': 2, 'S': 0, 'X': 2},
 datetime.date(2017, 2, 25): {'B': 1, 'M': 20, 'Q': 2, 'S': 0, 'X': 2},
 datetime.date(2017, 2, 26): {'B': 1, 'M': 20, 'Q': 2, 'S': 0, 'X': 2},
 datetime.date(2017, 2, 27): {'B': 3, 'M': 20, 'Q': 2, 'S': 0, 'X': 2},
 datetime.date(2017, 2, 28): {'B': 3, 'M': 31, 'Q': 2, 'S': 0, 'X': 2},
 datetime.date(2017, 3, 1): {'B': 3, 'M': 31, 'Q': 8, 'S': 0, 'X': 2},
 datetime.date(2017, 3, 2): {'B': 3, 'M': 31, 'Q': 8, 'S': 0, 'X': 2},
 datetime.date(2017, 3, 3): {'B': 3, 'M': 31, 'Q': 9, 'S': 0, 'X': 2},
 datetime.date(2017, 3, 4): {'B': 3, 'M': 31, 'Q': 9, 'S': 0, 'X': 2},
 datetime.date(2017, 3, 5): {'B': 3, 'M': 31, 'Q': 9, 'S': 0, 'X': 2},
 datetime.date(2017, 3, 6): {'B': 3, 'M': 31, 'Q': 9, 'S': 0, 'X': 5},
 datetime.date(2017, 3, 7): {'B': 3, 'M': 31, 'Q': 9, 'S': 0, 'X': 5},
 datetime.date(2017, 3, 8): {'B': 70, 'M': 31, 'Q': 9, 'S': 90, 'X': 5},
 datetime.date(2017, 3, 9): {'B': 70, 'M': 31, 'Q': 10, 'S': 90, 'X': 5},
 datetime.date(2017, 3, 10): {'B': 70, 'M': 32, 'Q': 10, 'S': 90, 'X': 8},
 datetime.date(2017, 3, 11): {'B': 70, 'M': 32, 'Q': 10, 'S': 90, 'X': 8},
 datetime.date(2017, 3, 12): {'B': 70, 'M': 32, 'Q': 10, 'S': 90, 'X': 8},
 datetime.date(2017, 3, 13): {'B': 70, 'M': 48, 'Q': 14, 'S': 90, 'X': 8},
 datetime.date(2017, 3, 14): {'B': 70, 'M': 48, 'Q': 14, 'S': 91, 'X': 8},
 datetime.date(2017, 3, 15): {'B': 70, 'M': 48, 'Q': 15, 'S': 91, 'X': 8},
 datetime.date(2017, 3, 16): {'B': 71, 'M': 48, 'Q': 15, 'S': 91, 'X': 11},
 datetime.date(2017, 3, 17): {'B': 83, 'M': 48, 'Q': 15, 'S': 91, 'X': 11},
 datetime.date(2017, 3, 18): {'B': 85, 'M': 48, 'Q': 15, 'S': 91, 'X': 11},
 datetime.date(2017, 3, 19): {'B': 85, 'M': 48, 'Q': 15, 'S': 91, 'X': 11},
 datetime.date(2017, 3, 20): {'B': 85, 'M': 48, 'Q': 15, 'S': 171, 'X': 11},
 datetime.date(2017, 3, 21): {'B': 85, 'M': 48, 'Q': 15, 'S': 171, 'X': 15},
 datetime.date(2017, 3, 22): {'B': 85, 'M': 48, 'Q': 15, 'S': 171, 'X': 15},
 datetime.date(2017, 3, 23): {'B': 91, 'M': 48, 'Q': 15, 'S': 171, 'X': 22},
 datetime.date(2017, 3, 24): {'B': 91, 'M': 48, 'Q': 16, 'S': 171, 'X': 22},
 datetime.date(2017, 3, 25): {'B': 91, 'M': 48, 'Q': 16, 'S': 171, 'X': 22},
 datetime.date(2017, 3, 26): {'B': 91, 'M': 48, 'Q': 18, 'S': 171, 'X': 22},
 datetime.date(2017, 3, 27): {'B': 91, 'M': 48, 'Q': 19, 'S': 171, 'X': 43},
 datetime.date(2017, 3, 28): {'B': 91, 'M': 48, 'Q': 20, 'S': 171, 'X': 44},
 datetime.date(2017, 3, 29): {'B': 92, 'M': 48, 'Q': 20, 'S': 171, 'X': 45},
 datetime.date(2017, 3, 30): {'B': 92, 'M': 50, 'Q': 20, 'S': 171, 'X': 45},
 datetime.date(2017, 3, 31): {'B': 93, 'M': 50, 'Q': 22, 'S': 171, 'X': 54},
 datetime.date(2017, 4, 1): {'B': 110, 'M': 65, 'Q': 45, 'S': 283, 'X': 63},
 datetime.date(2017, 4, 2): {'B': 125, 'M': 67, 'Q': 49, 'S': 283, 'X': 66},
 datetime.date(2017, 4, 3): {'B': 127, 'M': 69, 'Q': 49, 'S': 287, 'X': 75},
 datetime.date(2017, 4, 4): {'B': 133, 'M': 69, 'Q': 55, 'S': 287, 'X': 75},
 datetime.date(2017, 4, 5): {'B': 136, 'M': 72, 'Q': 59, 'S': 287, 'X': 75},
 datetime.date(2017, 4, 6): {'B': 137, 'M': 76, 'Q': 78, 'S': 287, 'X': 75},
 datetime.date(2017, 4, 7): {'B': 137, 'M': 76, 'Q': 86, 'S': 287, 'X': 87},
 datetime.date(2017, 4, 8): {'B': 137, 'M': 88, 'Q': 86, 'S': 287, 'X': 87},
 datetime.date(2017, 4, 9): {'B': 137, 'M': 89, 'Q': 86, 'S': 287, 'X': 87},
 datetime.date(2017, 4, 10): {'B': 138, 'M': 156, 'Q': 161, 'S': 302, 'X': 87},
 datetime.date(2017, 4, 11): {'B': 138, 'M': 161, 'Q': 167, 'S': 302, 'X': 90},
 datetime.date(2017, 4, 12): {'B': 138, 'M': 169, 'Q': 167, 'S': 302, 'X': 90},
 datetime.date(2017, 4, 13): {'B': 140, 'M': 169, 'Q': 170, 'S': 302, 'X': 90},
 datetime.date(2017, 4, 14): {'B': 140,
  'M': 175,
  'Q': 170,
  'S': 302,
  'X': 110},
 datetime.date(2017, 4, 15): {'B': 142,
  'M': 175,
  'Q': 176,
  'S': 330,
  'X': 110},
 datetime.date(2017, 4, 16): {'B': 142,
  'M': 185,
  'Q': 178,
  'S': 330,
  'X': 110},
 datetime.date(2017, 4, 17): {'B': 156,
  'M': 196,
  'Q': 243,
  'S': 378,
  'X': 192},
 datetime.date(2017, 4, 18): {'B': 156,
  'M': 201,
  'Q': 243,
  'S': 378,
  'X': 192},
 datetime.date(2017, 4, 19): {'B': 184,
  'M': 204,
  'Q': 257,
  'S': 407,
  'X': 194},
 datetime.date(2017, 4, 20): {'B': 186,
  'M': 204,
  'Q': 257,
  'S': 407,
  'X': 219},
 datetime.date(2017, 4, 21): {'B': 187,
  'M': 205,
  'Q': 257,
  'S': 407,
  'X': 222},
 datetime.date(2017, 4, 22): {'B': 193,
  'M': 239,
  'Q': 262,
  'S': 407,
  'X': 222},
 datetime.date(2017, 4, 23): {'B': 193,
  'M': 239,
  'Q': 270,
  'S': 407,
  'X': 222},
 datetime.date(2017, 4, 24): {'B': 242,
  'M': 251,
  'Q': 270,
  'S': 467,
  'X': 222},
 datetime.date(2017, 4, 25): {'B': 247,
  'M': 254,
  'Q': 271,
  'S': 467,
  'X': 222},
 datetime.date(2017, 4, 26): {'B': 264,
  'M': 295,
  'Q': 275,
  'S': 504,
  'X': 231},
 datetime.date(2017, 4, 27): {'B': 293,
  'M': 318,
  'Q': 278,
  'S': 526,
  'X': 277},
 datetime.date(2017, 4, 28): {'B': 321,
  'M': 365,
  'Q': 358,
  'S': 526,
  'X': 280},
 datetime.date(2017, 4, 29): {'B': 250,
  'M': 399,
  'Q': 360,
  'S': 526,
  'X': 280},
 datetime.date(2017, 4, 30): {'B': 251,
  'M': 405,
  'Q': 355,
  'S': 526,
  'X': 280},
 datetime.date(2017, 5, 1): {'B': 297, 'M': 431, 'Q': 430, 'S': 446, 'X': 285},
 datetime.date(2017, 5, 2): {'B': 281, 'M': 366, 'Q': 423, 'S': 458, 'X': 283},
 datetime.date(2017, 5, 3): {'B': 292, 'M': 382, 'Q': 423, 'S': 479, 'X': 284},
 datetime.date(2017, 5, 4): {'B': 298, 'M': 374, 'Q': 429, 'S': 479, 'X': 300},
 datetime.date(2017, 5, 5): {'B': 320, 'M': 378, 'Q': 420, 'S': 479, 'X': 289},
 datetime.date(2017, 5, 6): {'B': 292, 'M': 378, 'Q': 422, 'S': 479, 'X': 289},
 datetime.date(2017, 5, 7): {'B': 290, 'M': 388, 'Q': 420, 'S': 479, 'X': 280},
 datetime.date(2017, 5, 8): {'B': 380, 'M': 410, 'Q': 474, 'S': 504, 'X': 308},
 datetime.date(2017, 5, 9): {'B': 311, 'M': 337, 'Q': 448, 'S': 441, 'X': 306},
 datetime.date(2017, 5, 10): {'B': 326,
  'M': 330,
  'Q': 448,
  'S': 475,
  'X': 306},
 datetime.date(2017, 5, 11): {'B': 351,
  'M': 340,
  'Q': 451,
  'S': 475,
  'X': 310},
 datetime.date(2017, 5, 12): {'B': 389,
  'M': 343,
  'Q': 448,
  'S': 495,
  'X': 322},
 datetime.date(2017, 5, 13): {'B': 322,
  'M': 380,
  'Q': 442,
  'S': 495,
  'X': 319},
 datetime.date(2017, 5, 14): {'B': 320,
  'M': 385,
  'Q': 442,
  'S': 495,
  'X': 319},
 datetime.date(2017, 5, 15): {'B': 312,
  'M': 282,
  'Q': 663,
  'S': 497,
  'X': 319},
 datetime.date(2017, 5, 16): {'B': 296,
  'M': 190,
  'Q': 614,
  'S': 432,
  'X': 336},
 datetime.date(2017, 5, 17): {'B': 296,
  'M': 188,
  'Q': 616,
  'S': 539,
  'X': 319},
 datetime.date(2017, 5, 18): {'B': 303,
  'M': 203,
  'Q': 626,
  'S': 539,
  'X': 337},
 datetime.date(2017, 5, 19): {'B': 315,
  'M': 202,
  'Q': 632,
  'S': 554,
  'X': 335},
 datetime.date(2017, 5, 20): {'B': 313,
  'M': 282,
  'Q': 634,
  'S': 554,
  'X': 335},
 datetime.date(2017, 5, 21): {'B': 310,
  'M': 275,
  'Q': 639,
  'S': 554,
  'X': 326},
 datetime.date(2017, 5, 22): {'B': 349,
  'M': 279,
  'Q': 640,
  'S': 554,
  'X': 326},
 datetime.date(2017, 5, 23): {'B': 303,
  'M': 235,
  'Q': 535,
  'S': 525,
  'X': 326},
 datetime.date(2017, 5, 24): {'B': 326,
  'M': 224,
  'Q': 598,
  'S': 499,
  'X': 330},
 datetime.date(2017, 5, 25): {'B': 339,
  'M': 264,
  'Q': 595,
  'S': 499,
  'X': 318},
 datetime.date(2017, 5, 26): {'B': 328,
  'M': 275,
  'Q': 595,
  'S': 499,
  'X': 318},
 datetime.date(2017, 5, 27): {'B': 316,
  'M': 270,
  'Q': 586,
  'S': 499,
  'X': 318},
 datetime.date(2017, 5, 28): {'B': 314,
  'M': 259,
  'Q': 584,
  'S': 499,
  'X': 327},
 datetime.date(2017, 5, 29): {'B': 313,
  'M': 251,
  'Q': 575,
  'S': 499,
  'X': 318},
 datetime.date(2017, 5, 30): {'B': 289,
  'M': 199,
  'Q': 589,
  'S': 449,
  'X': 326},
 datetime.date(2017, 5, 31): {'B': 283,
  'M': 210,
  'Q': 590,
  'S': 429,
  'X': 341},
 datetime.date(2017, 6, 1): {'B': 319, 'M': 280, 'Q': 590, 'S': 407, 'X': 344},
 datetime.date(2017, 6, 2): {'B': 371, 'M': 263, 'Q': 675, 'S': 407, 'X': 344},
 datetime.date(2017, 6, 3): {'B': 368, 'M': 310, 'Q': 648, 'S': 409, 'X': 342},
 datetime.date(2017, 6, 4): {'B': 357, 'M': 311, 'Q': 636, 'S': 409, 'X': 353},
 datetime.date(2017, 6, 5): {'B': 348, 'M': 319, 'Q': 712, 'S': 409, 'X': 342},
 datetime.date(2017, 6, 6): {'B': 278, 'M': 278, 'Q': 612, 'S': 424, 'X': 337},
 datetime.date(2017, 6, 7): {'B': 302, 'M': 259, 'Q': 617, 'S': 482, 'X': 357},
 datetime.date(2017, 6, 8): {'B': 302, 'M': 273, 'Q': 612, 'S': 492, 'X': 359},
 datetime.date(2017, 6, 9): {'B': 362, 'M': 351, 'Q': 612, 'S': 507, 'X': 373},
 datetime.date(2017, 6, 10): {'B': 275,
  'M': 393,
  'Q': 610,
  'S': 513,
  'X': 370},
 datetime.date(2017, 6, 11): {'B': 272,
  'M': 393,
  'Q': 619,
  'S': 513,
  'X': 358},
 datetime.date(2017, 6, 12): {'B': 298,
  'M': 410,
  'Q': 603,
  'S': 559,
  'X': 358},
 datetime.date(2017, 6, 13): {'B': 294,
  'M': 369,
  'Q': 533,
  'S': 544,
  'X': 348},
 datetime.date(2017, 6, 14): {'B': 293,
  'M': 390,
  'Q': 536,
  'S': 546,
  'X': 352},
 datetime.date(2017, 6, 15): {'B': 310,
  'M': 413,
  'Q': 536,
  'S': 537,
  'X': 350},
 datetime.date(2017, 6, 16): {'B': 300,
  'M': 400,
  'Q': 539,
  'S': 558,
  'X': 371},
 datetime.date(2017, 6, 17): {'B': 228,
  'M': 439,
  'Q': 539,
  'S': 558,
  'X': 353},
 datetime.date(2017, 6, 18): {'B': 226,
  'M': 421,
  'Q': 540,
  'S': 538,
  'X': 353},
 datetime.date(2017, 6, 19): {'B': 309,
  'M': 413,
  'Q': 539,
  'S': 540,
  'X': 357},
 datetime.date(2017, 6, 20): {'B': 277,
  'M': 329,
  'Q': 372,
  'S': 528,
  'X': 358},
 datetime.date(2017, 6, 21): {'B': 269,
  'M': 318,
  'Q': 367,
  'S': 510,
  'X': 372},
 datetime.date(2017, 6, 22): {'B': 273,
  'M': 327,
  'Q': 369,
  'S': 489,
  'X': 362},
 datetime.date(2017, 6, 23): {'B': 268,
  'M': 332,
  'Q': 370,
  'S': 489,
  'X': 362},
 datetime.date(2017, 6, 24): {'B': 223,
  'M': 393,
  'Q': 368,
  'S': 489,
  'X': 355},
 datetime.date(2017, 6, 25): {'B': 219,
  'M': 380,
  'Q': 369,
  'S': 491,
  'X': 341},
 datetime.date(2017, 6, 26): {'B': 229,
  'M': 381,
  'Q': 449,
  'S': 491,
  'X': 341},
 datetime.date(2017, 6, 27): {'B': 247,
  'M': 317,
  'Q': 388,
  'S': 491,
  'X': 350},
 datetime.date(2017, 6, 28): {'B': 240,
  'M': 323,
  'Q': 407,
  'S': 491,
  'X': 369},
 datetime.date(2017, 6, 29): {'B': 230,
  'M': 338,
  'Q': 409,
  'S': 493,
  'X': 378},
 datetime.date(2017, 6, 30): {'B': 253,
  'M': 357,
  'Q': 515,
  'S': 501,
  'X': 383},
 datetime.date(2017, 7, 1): {'B': 217, 'M': 382, 'Q': 472, 'S': 327, 'X': 400},
 datetime.date(2017, 7, 2): {'B': 189, 'M': 328, 'Q': 472, 'S': 372, 'X': 365},
 datetime.date(2017, 7, 3): {'B': 179, 'M': 330, 'Q': 467, 'S': 295, 'X': 365},
 datetime.date(2017, 7, 4): {'B': 158, 'M': 324, 'Q': 418, 'S': 293, 'X': 374},
 datetime.date(2017, 7, 5): {'B': 228, 'M': 335, 'Q': 418, 'S': 293, 'X': 367},
 datetime.date(2017, 7, 6): {'B': 232, 'M': 335, 'Q': 421, 'S': 328, 'X': 353},
 datetime.date(2017, 7, 7): {'B': 235, 'M': 356, 'Q': 421, 'S': 308, 'X': 353},
 datetime.date(2017, 7, 8): {'B': 222, 'M': 394, 'Q': 421, 'S': 308, 'X': 356},
 datetime.date(2017, 7, 9): {'B': 214, 'M': 382, 'Q': 425, 'S': 310, 'X': 353},
 datetime.date(2017, 7, 10): {'B': 275,
  'M': 363,
  'Q': 528,
  'S': 290,
  'X': 353},
 datetime.date(2017, 7, 11): {'B': 267,
  'M': 352,
  'Q': 532,
  'S': 291,
  'X': 355},
 datetime.date(2017, 7, 12): {'B': 277,
  'M': 350,
  'Q': 534,
  'S': 349,
  'X': 355},
 datetime.date(2017, 7, 13): {'B': 277,
  'M': 324,
  'Q': 536,
  'S': 349,
  'X': 355},
 datetime.date(2017, 7, 14): {'B': 299,
  'M': 340,
  'Q': 530,
  'S': 347,
  'X': 358},
 datetime.date(2017, 7, 15): {'B': 250,
  'M': 373,
  'Q': 528,
  'S': 347,
  'X': 360},
 datetime.date(2017, 7, 16): {'B': 247,
  'M': 370,
  'Q': 528,
  'S': 347,
  'X': 301},
 datetime.date(2017, 7, 17): {'B': 297,
  'M': 374,
  'Q': 526,
  'S': 340,
  'X': 303},
 datetime.date(2017, 7, 18): {'B': 258,
  'M': 345,
  'Q': 525,
  'S': 341,
  'X': 303},
 datetime.date(2017, 7, 19): {'B': 287,
  'M': 337,
  'Q': 533,
  'S': 341,
  'X': 263},
 datetime.date(2017, 7, 20): {'B': 313,
  'M': 359,
  'Q': 702,
  'S': 465,
  'X': 264},
 datetime.date(2017, 7, 21): {'B': 308,
  'M': 358,
  'Q': 704,
  'S': 465,
  'X': 260},
 datetime.date(2017, 7, 22): {'B': 305,
  'M': 407,
  'Q': 700,
  'S': 463,
  'X': 268},
 datetime.date(2017, 7, 23): {'B': 302,
  'M': 403,
  'Q': 691,
  'S': 463,
  'X': 259},
 datetime.date(2017, 7, 24): {'B': 301,
  'M': 407,
  'Q': 698,
  'S': 460,
  'X': 259},
 datetime.date(2017, 7, 25): {'B': 264,
  'M': 361,
  'Q': 696,
  'S': 460,
  'X': 257},
 datetime.date(2017, 7, 26): {'B': 281,
  'M': 372,
  'Q': 696,
  'S': 470,
  'X': 211},
 datetime.date(2017, 7, 27): {'B': 287,
  'M': 371,
  'Q': 702,
  'S': 470,
  'X': 211},
 datetime.date(2017, 7, 28): {'B': 296,
  'M': 365,
  'Q': 702,
  'S': 470,
  'X': 234},
 datetime.date(2017, 7, 29): {'B': 281,
  'M': 424,
  'Q': 706,
  'S': 470,
  'X': 254},
 datetime.date(2017, 7, 30): {'B': 282,
  'M': 418,
  'Q': 706,
  'S': 468,
  'X': 241},
 datetime.date(2017, 7, 31): {'B': 317,
  'M': 432,
  'Q': 726,
  'S': 439,
  'X': 244},
 datetime.date(2017, 8, 1): {'B': 293, 'M': 337, 'Q': 814, 'S': 380, 'X': 227},
 datetime.date(2017, 8, 2): {'B': 331, 'M': 344, 'Q': 825, 'S': 381, 'X': 256},
 datetime.date(2017, 8, 3): {'B': 317, 'M': 344, 'Q': 815, 'S': 437, 'X': 254},
 datetime.date(2017, 8, 4): {'B': 338, 'M': 367, 'Q': 815, 'S': 437, 'X': 266},
 datetime.date(2017, 8, 5): {'B': 345, 'M': 392, 'Q': 823, 'S': 437, 'X': 249},
 datetime.date(2017, 8, 6): {'B': 343, 'M': 427, 'Q': 805, 'S': 435, 'X': 238},
 datetime.date(2017, 8, 7): {'B': 362, 'M': 420, 'Q': 806, 'S': 430, 'X': 236},
 datetime.date(2017, 8, 8): {'B': 311, 'M': 388, 'Q': 720, 'S': 418, 'X': 232},
 datetime.date(2017, 8, 9): {'B': 303, 'M': 321, 'Q': 722, 'S': 429, 'X': 284},
 datetime.date(2017, 8, 10): {'B': 310,
  'M': 336,
  'Q': 722,
  'S': 429,
  'X': 278},
 datetime.date(2017, 8, 11): {'B': 303,
  'M': 333,
  'Q': 821,
  'S': 428,
  'X': 274},
 datetime.date(2017, 8, 12): {'B': 282,
  'M': 353,
  'Q': 819,
  'S': 428,
  'X': 274},
 datetime.date(2017, 8, 13): {'B': 267,
  'M': 376,
  'Q': 815,
  'S': 427,
  'X': 274},
 datetime.date(2017, 8, 14): {'B': 294,
  'M': 365,
  'Q': 772,
  'S': 423,
  'X': 274},
 datetime.date(2017, 8, 15): {'B': 329,
  'M': 304,
  'Q': 749,
  'S': 392,
  'X': 265},
 datetime.date(2017, 8, 16): {'B': 334,
  'M': 303,
  'Q': 759,
  'S': 335,
  'X': 268},
 datetime.date(2017, 8, 17): {'B': 367,
  'M': 310,
  'Q': 756,
  'S': 364,
  'X': 251},
 datetime.date(2017, 8, 18): {'B': 369,
  'M': 338,
  'Q': 760,
  'S': 364,
  'X': 330},
 datetime.date(2017, 8, 19): {'B': 362,
  'M': 397,
  'Q': 654,
  'S': 364,
  'X': 326},
 datetime.date(2017, 8, 20): {'B': 356,
  'M': 422,
  'Q': 645,
  'S': 364,
  'X': 324},
 datetime.date(2017, 8, 21): {'B': 367,
  'M': 430,
  'Q': 799,
  'S': 364,
  'X': 325},
 datetime.date(2017, 8, 22): {'B': 357,
  'M': 382,
  'Q': 793,
  'S': 320,
  'X': 328},
 datetime.date(2017, 8, 23): {'B': 380,
  'M': 369,
  'Q': 806,
  'S': 352,
  'X': 327},
 datetime.date(2017, 8, 24): {'B': 399,
  'M': 364,
  'Q': 804,
  'S': 358,
  'X': 325},
 datetime.date(2017, 8, 25): {'B': 399,
  'M': 361,
  'Q': 805,
  'S': 348,
  'X': 325},
 datetime.date(2017, 8, 26): {'B': 393,
  'M': 418,
  'Q': 817,
  'S': 348,
  'X': 325},
 datetime.date(2017, 8, 27): {'B': 381,
  'M': 413,
  'Q': 826,
  'S': 348,
  'X': 325},
 datetime.date(2017, 8, 28): {'B': 404,
  'M': 429,
  'Q': 811,
  'S': 356,
  'X': 325},
 datetime.date(2017, 8, 29): {'B': 302,
  'M': 344,
  'Q': 730,
  'S': 335,
  'X': 320},
 datetime.date(2017, 8, 30): {'B': 291,
  'M': 334,
  'Q': 739,
  'S': 365,
  'X': 354},
 datetime.date(2017, 8, 31): {'B': 293,
  'M': 342,
  'Q': 763,
  'S': 393,
  'X': 354},
 datetime.date(2017, 9, 1): {'B': 279, 'M': 345, 'Q': 545, 'S': 373, 'X': 372},
 datetime.date(2017, 9, 2): {'B': 263, 'M': 321, 'Q': 529, 'S': 365, 'X': 369},
 datetime.date(2017, 9, 3): {'B': 257, 'M': 301, 'Q': 521, 'S': 364, 'X': 363},
 datetime.date(2017, 9, 4): {'B': 263, 'M': 301, 'Q': 516, 'S': 364, 'X': 363},
 datetime.date(2017, 9, 5): {'B': 295, 'M': 270, 'Q': 510, 'S': 272, 'X': 349},
 datetime.date(2017, 9, 6): {'B': 274, 'M': 253, 'Q': 512, 'S': 274, 'X': 351},
 datetime.date(2017, 9, 7): {'B': 291, 'M': 248, 'Q': 529, 'S': 290, 'X': 356},
 datetime.date(2017, 9, 8): {'B': 317, 'M': 247, 'Q': 533, 'S': 290, 'X': 356},
 datetime.date(2017, 9, 9): {'B': 312, 'M': 311, 'Q': 400, 'S': 290, 'X': 366},
 datetime.date(2017, 9, 10): {'B': 312,
  'M': 308,
  'Q': 398,
  'S': 284,
  'X': 367},
 datetime.date(2017, 9, 11): {'B': 327,
  'M': 321,
  'Q': 386,
  'S': 285,
  'X': 362},
 datetime.date(2017, 9, 12): {'B': 331,
  'M': 249,
  'Q': 373,
  'S': 264,
  'X': 349},
 datetime.date(2017, 9, 13): {'B': 337,
  'M': 254,
  'Q': 381,
  'S': 322,
  'X': 354},
 datetime.date(2017, 9, 14): {'B': 422,
  'M': 254,
  'Q': 379,
  'S': 326,
  'X': 349},
 datetime.date(2017, 9, 15): {'B': 424,
  'M': 264,
  'Q': 376,
  'S': 326,
  'X': 350},
 datetime.date(2017, 9, 16): {'B': 374,
  'M': 307,
  'Q': 373,
  'S': 326,
  'X': 362},
 datetime.date(2017, 9, 17): {'B': 369,
  'M': 315,
  'Q': 373,
  'S': 325,
  'X': 342},
 datetime.date(2017, 9, 18): {'B': 415,
  'M': 359,
  'Q': 618,
  'S': 325,
  'X': 364},
 datetime.date(2017, 9, 19): {'B': 383,
  'M': 242,
  'Q': 610,
  'S': 310,
  'X': 375},
 datetime.date(2017, 9, 20): {'B': 404,
  'M': 252,
  'Q': 1058,
  'S': 348,
  'X': 368},
 datetime.date(2017, 9, 21): {'B': 390,
  'M': 246,
  'Q': 1064,
  'S': 351,
  'X': 354},
 datetime.date(2017, 9, 22): {'B': 383,
  'M': 266,
  'Q': 1066,
  'S': 355,
  'X': 356},
 datetime.date(2017, 9, 23): {'B': 309,
  'M': 298,
  'Q': 994,
  'S': 351,
  'X': 358},
 datetime.date(2017, 9, 24): {'B': 311,
  'M': 295,
  'Q': 988,
  'S': 347,
  'X': 358},
 datetime.date(2017, 9, 25): {'B': 345,
  'M': 323,
  'Q': 1005,
  'S': 489,
  'X': 380},
 datetime.date(2017, 9, 26): {'B': 373,
  'M': 256,
  'Q': 1005,
  'S': 476,
  'X': 355},
 datetime.date(2017, 9, 27): {'B': 417,
  'M': 265,
  'Q': 1005,
  'S': 476,
  'X': 356},
 datetime.date(2017, 9, 28): {'B': 446,
  'M': 289,
  'Q': 1024,
  'S': 517,
  'X': 372},
 datetime.date(2017, 9, 29): {'B': 547,
  'M': 294,
  'Q': 1007,
  'S': 530,
  'X': 357},
 datetime.date(2017, 9, 30): {'B': 485,
  'M': 339,
  'Q': 1009,
  'S': 545,

In [192]:
#M: manhattan, X: Bronx, B: Brooklyn, Q: Queens, S: Staten Island
M_arr = [0]*df.shape[0]
X_arr = [0]*df.shape[0]
B_arr = [0]*df.shape[0]
Q_arr = [0]*df.shape[0]
S_arr = [0]*df.shape[0]

In [193]:
df.head

<bound method NDFrame.head of          VendorID tpep_pickup_datetime tpep_dropoff_datetime  passenger_count  \
0               1  2018-01-01 00:21:05   2018-01-01 00:24:23                1
1               1  2018-01-01 00:44:55   2018-01-01 01:03:05                1
2               1  2018-01-01 00:08:26   2018-01-01 00:14:21                2
3               1  2018-01-01 00:20:22   2018-01-01 00:52:51                1
4               1  2018-01-01 00:09:18   2018-01-01 00:27:06                2
5               1  2018-01-01 00:29:29   2018-01-01 00:32:48                3
6               1  2018-01-01 00:38:08   2018-01-01 00:48:24                2
7               1  2018-01-01 00:49:29   2018-01-01 00:51:53                1
8               1  2018-01-01 00:56:38   2018-01-01 01:01:05                1
9               1  2018-01-01 00:17:04   2018-01-01 00:22:24                1
10              1  2018-01-01 00:41:03   2018-01-01 00:46:49                1
11              1  2018-01-01 00:52:54   2018-01-01 01:17:33                1
12              2  2018-01-01 00:17:54   2018-01-01 00:22:05                1
13              2  2018-01-01 00:24:47   2018-01-01 00:34:20                1
14              2  2018-01-01 00:37:57   2018-01-01 00:53:43                1
15              1  2018-01-01 00:35:53   2018-01-01 00:52:59                1
16              2  2018-01-01 00:30:47   2018-01-01 01:13:20                1
17              1  2018-01-01 00:21:45   2018-01-01 00:25:58                2
18              1  2018-01-01 00:31:11   2018-01-01 01:07:56                1
19              2  2018-01-01 00:15:42   2018-01-01 00:21:38                5
20              2  2018-01-01 00:25:19   2018-01-01 00:45:02                5
21              2  2018-01-01 00:51:36   2018-01-01 01:04:13                5
22              2  2018-01-01 00:09:11   2018-01-01 00:30:24                1
23              2  2018-01-01 00:32:00   2018-01-01 00:58:50                1
24              1  2018-01-01 00:41:49   2018-01-01 00:54:44                4
25              2  2018-01-01 00:17:15   2018-01-01 00:21:49                5
26              2  2018-01-01 00:24:54   2018-01-01 00:46:55                5
27              2  2018-01-01 00:48:40   2018-01-01 00:51:30                5
28              1  2018-01-01 00:24:42   2018-01-01 00:31:56                2
29              1  2018-01-01 00:36:09   2018-01-01 00:43:06                1
...           ...                  ...                   ...              ...
8759844         2  2018-01-31 23:40:38   2018-01-31 23:43:50                1
8759845         2  2018-01-31 23:53:03   2018-02-01 00:09:22                1
8759846         2  2018-01-31 23:31:18   2018-01-31 23:43:41                2
8759847         2  2018-01-31 23:55:15   2018-02-01 00:06:49                3
8759848         1  2018-01-31 23:08:35   2018-01-31 23:16:05                1
8759849         2  2018-01-31 23:03:31   2018-01-31 23:17:20                3
8759850         2  2018-01-31 23:28:47   2018-01-31 23:35:54                3
8759851         2  2018-01-31 23:01:38   2018-01-31 23:24:36                1
8759852         2  2018-01-31 23:35:33   2018-02-01 00:04:11                1
8759853         2  2018-01-31 23:11:36   2018-01-31 23:33:28                1
8759854         2  2018-01-31 23:37:29   2018-01-31 23:51:45                1
8759855         2  2018-01-31 23:39:15   2018-01-31 23:43:37                1
8759856         2  2018-01-31 23:25:02   2018-01-31 23:55:33                1
8759857         1  2018-01-31 23:17:00   2018-01-31 23:24:37                1
8759858         1  2018-01-31 23:26:11   2018-01-31 23:29:53                1
8759859         2  2018-01-31 23:11:59   2018-01-31 23:31:33                2
8759860         1  2018-01-31 23:54:57   2018-02-01 00:29:56                1
8759861         2  2018-01-31 23:11:56   2018-01-31 23:13:53                1
8759862         2  2018-01-31 23:16:59   2018-01-31 23:23:10                1
8759863         2  2018-01-31 23:08:48   2018-01-31 23:24:17                1
8759864         1  2018-01-31 23:05:11   2018-01-31 23:13:53                1
8759865         1  2018-01-31 23:41:11   2018-01-31 23:45:22                1
8759866         1  2018-01-31 23:52:53   2018-01-31 23:57:32                1
8759867         2  2018-01-31 23:20:51   2018-01-31 23:30:51                1
8759868         2  2018-01-31 23:57:33   2018-02-01 00:07:44                1
8759869         1  2018-01-31 23:21:35   2018-01-31 23:34:20                2
8759870         1  2018-01-31 23:35:51   2018-01-31 23:38:57                1
8759871         2  2018-01-31 23:28:00   2018-01-31 23:37:09                1
8759872         2  2018-01-31 23:24:40   2018-01-31 23:25:28                1
8759873         2  2018-01-31 23:28:16   2018-01-31 23:28:38                1

         trip_distance  RatecodeID store_and_fwd_flag  PULocationID  \
0                 0.50           1                  N            41
1                 2.70           1                  N           239
2                 0.80           1                  N           262
3                10.20           1                  N           140
4                 2.50           1                  N           246
5                 0.50           1                  N           143
6                 1.70           1                  N            50
7                 0.70           1                  N           239
8                 1.00           1                  N           238
9                 0.70           1                  N           170
10                0.60           1                  N           162
11                3.50           1                  N           141
12                1.04           1                  N           137
13                1.22           1                  N           224
14                1.92           1                  N           234
15                5.70           1                  N            13
16                3.74           1                  N            48
17                0.60           1                  N           163
18               10.90           1                  N           229
19                1.22           1                  N           236
20                3.13           1                  N           263
21                2.22           1                  N           239
22                2.93           1                  N            90
23                3.52           1                  N           233
24                3.00           1                  N           161
25                0.25           1                  N           234
26                3.31           1                  N           234
27                0.57           1                  N           142
28                0.70           1                  N           170
29                1.80           1                  N           233
...                ...         ...                ...           ...
8759844           0.74           1                  N           234
8759845           5.09           1                  N            68
8759846           3.70           1                  N           209
8759847           2.48           1                  N           211
8759848           1.90           1                  N            43
8759849           4.00           1                  N           158
8759850           0.75           1                  N           231
8759851           4.29           1                  N            90
8759852           4.92           1                  N           148
8759853           4.64           1                  N           161
8759854           4.10           1                  N            88
8759855           0.77           1                  N           142
8759856          10.69           1                  N           138
8759857           1.00           1                  N           230
8759858           0.70           1                  N           100
8759859          13.36           1                  N           138
8759860          13.90           1                  N           186
8759861           0.75           1                  N           238
8759862           1.58           1                  N           151
8759863           2.63           1                  N           238
8759864           2.60           1                  N           137
8759865           0.30           1                  N           163
8759866           1.20           1                  N            43
8759867           1.65           1                  N           234
8759868           2.92           1                  N           230
8759869           2.80           1                  N           158
8759870           0.60           1                  N           163
8759871           2.95           1                  N            74
8759872           0.00           1                  N             7
8759873           0.00           1                  N             7

         DOLocationID  payment_type  fare_amount  extra  mta_tax  tip_amount  \
0                  24             2          4.5    0.5      0.5        0.00
1                 140             2         14.0    0.5      0.5        0.00
2                 141             1          6.0    0.5      0.5        1.00
3                 257             2         33.5    0.5      0.5        0.00
4                 239             1         12.5    0.5      0.5        2.75
5                 143             2          4.5    0.5      0.5        0.00
6                 239             1          9.0    0.5      0.5        2.05
7                 238             1          4.0    0.5      0.5        1.00
8                  24             1          5.5    0.5      0.5        1.70
9                 170             2          5.5    0.5      0.5        0.00
10                229             1          5.5    0.5      0.5        1.35
11                113             2         16.5    0.5      0.5        0.00
12                224             2          5.5    0.5      0.5        0.00
13                 79             2          7.5    0.5      0.5        0.00
14                100             2         10.0    0.5      0.5        0.00
15                189             1         19.0    0.5      0.5        4.05
16                236             1         25.5    0.5      0.5        6.70
17                162             1          4.5    0.5      0.5        1.70
18                 61             2         35.0    0.5      0.5        0.00
19                 75             2          6.0    0.5      0.5        0.00
20                143             2         13.0    0.5      0.5        0.00
21                 24             2          9.5    0.5      0.5        0.00
22                233             1         14.5    0.5      0.5        2.00
23                125             2         18.0    0.5      0.5        0.00
24                146             1         12.0    0.5      0.5        2.65
25                234             2          4.5    0.5      0.5        0.00
26                143             1         16.0    0.5      0.5        3.46
27                239             1          4.0    0.5      0.5        1.06
28                162             2          6.0    0.5      0.5        0.00
29                263             2          7.5    0.5      0.5        0.00
...               ...           ...          ...    ...      ...         ...
8759844           186             2          4.5    0.5      0.5        0.00
8759845           209             1         18.0    0.5      0.5        3.86
8759846           114             1         13.5    0.5      0.5        2.50
8759847           186             1         10.5    0.5      0.5        2.36
8759848           263             1          8.5    0.5      0.5        1.95
8759849            88             1         14.5    0.5      0.5        3.16
8759850           231             2          6.5    0.5      0.5        0.00
8759851           256             1         18.5    0.5      0.5        3.96
8759852           163             2         21.5    0.5      0.5        0.00
8759853           261             2         18.0    0.5      0.5        0.00
8759854            97             1         14.5    0.5      0.5        3.95
8759855           230             2          5.0    0.5      0.5        0.00
8759856           230             1         34.5    0.5      0.5        5.00
8759857            48             1          6.5    0.5      0.5        1.55
8759858           230             1          4.5    0.5      0.5        0.01
8759859            64             1         36.5    0.5      0.5        7.56
8759860            16             1         42.0    0.5      0.5       15.00
8759861           151             2          4.0    0.5      0.5        0.00
8759862            41             2          7.5    0.5      0.5        0.00
8759863            48             2         12.5    0.5      0.5        0.00
8759864           148             2         10.0    0.5      0.5        0.00
8759865           230             2          4.5    0.5      0.5        0.00
8759866           162             1          6.0    0.5      0.5        1.50
8759867           158             1          8.5    0.5      0.5        2.45
8759868           238             2         11.0    0.5      0.5        0.00
8759869           163             1         12.0    0.5      0.5        2.65
8759870           162             1          4.5    0.5      0.5        1.15
8759871            69             2         10.5    0.5      0.5        0.00
8759872           193             2          0.0    0.0      0.0        0.00
8759873           193             2          0.0    0.0      0.0        0.00

         tolls_amount  improvement_surcharge  total_amount
0                0.00                    0.3          5.80
1                0.00                    0.3         15.30
2                0.00                    0.3          8.30
3                0.00                    0.3         34.80
4                0.00                    0.3         16.55
5                0.00                    0.3          5.80
6                0.00                    0.3         12.35
7                0.00                    0.3          6.30
8                0.00                    0.3          8.50
9                0.00                    0.3          6.80
10               0.00                    0.3          8.15
11               0.00                    0.3         17.80
12               0.00                    0.3          6.80
13               0.00                    0.3          8.80
14               0.00                    0.3         11.30
15               0.00                    0.3         24.35
16               0.00                    0.3         33.50
17               0.00                    0.3          7.50
18               0.00                    0.3         36.30
19               0.00                    0.3          7.30
20               0.00                    0.3         14.30
21               0.00                    0.3         10.80
22               0.00                    0.3         17.80
23               0.00                    0.3         19.30
24               0.00                    0.3         15.95
25               0.00                    0.3          5.80
26               0.00                    0.3         20.76
27               0.00                    0.3          6.36
28               0.00                    0.3          7.30
29               0.00                    0.3          8.80
...               ...                    ...           ...
8759844          0.00                    0.3          5.80
8759845          0.00                    0.3         23.16
8759846          0.00                    0.3         17.30
8759847          0.00                    0.3         14.16
8759848          0.00                    0.3         11.75
8759849          0.00                    0.3         18.96
8759850          0.00                    0.3          7.80
8759851          0.00                    0.3         23.76
8759852          0.00                    0.3         22.80
8759853          0.00                    0.3         19.30
8759854          0.00                    0.3         19.75
8759855          0.00                    0.3          6.30
8759856          5.76                    0.3         46.56
8759857          0.00                    0.3          9.35
8759858          0.00                    0.3          5.81
8759859          0.00                    0.3         45.36
8759860          5.76                    0.3         64.06
8759861          0.00                    0.3          5.30
8759862          0.00                    0.3          8.80
8759863          0.00                    0.3         13.80
8759864          0.00                    0.3         11.30
8759865          0.00                    0.3          5.80
8759866          0.00                    0.3          8.80
8759867          0.00                    0.3         12.25
8759868          0.00                    0.3         12.30
8759869          0.00                    0.3         15.95
8759870          0.00                    0.3          6.95
8759871          0.00                    0.3         11.80
8759872          0.00                    0.0          0.00
8759873          0.00                    0.0          0.00

[8759874 rows x 17 columns]>

In [199]:
for index, row in df.iterrows():
    date = pd.Timestamp(row["tpep_pickup_datetime"]).date()
    if(date not in date_construction_num):
        print(date)
        continue
    M_arr[index] = date_construction_num[date]["M"]
    X_arr[index] = date_construction_num[date]["X"]
    B_arr[index] = date_construction_num[date]["B"]
    Q_arr[index] = date_construction_num[date]["Q"]
    S_arr[index] = date_construction_num[date]["S"]

2002-12-31
2017-01-02
2008-12-31
2009-01-01
2008-12-31
2008-12-31
2009-01-01
2008-12-31
2002-12-31
2009-01-01
2017-01-03
2001-01-05
2003-01-01
2003-01-01
2009-01-01
2008-12-31
2008-12-31
2009-01-01
2002-12-31
2003-01-01
2003-01-01
2002-12-31
2009-01-01
2003-01-01
2002-12-31
2008-12-31
2008-12-31
2008-12-31
2009-01-01
2009-01-01
2009-01-01
2009-01-01
2009-01-01
2009-01-01
2008-12-31
2008-12-31
2009-01-01
2009-01-01
2009-01-01
2009-01-01
2009-01-01

In [202]:
df['M'] = pd.Series(M_arr, index=df.index)

In [204]:
df['X'] = pd.Series(X_arr, index=df.index)
df['B'] = pd.Series(B_arr, index=df.index)
df['Q'] = pd.Series(Q_arr, index=df.index)
df['S'] = pd.Series(S_arr, index=df.index)

In [205]:
df.iloc[0]

VendorID                                   1
tpep_pickup_datetime     2018-01-01 00:21:05
tpep_dropoff_datetime    2018-01-01 00:24:23
passenger_count                            1
trip_distance                            0.5
RatecodeID                                 1
store_and_fwd_flag                         N
PULocationID                              41
DOLocationID                              24
payment_type                               2
fare_amount                              4.5
extra                                    0.5
mta_tax                                  0.5
tip_amount                                 0
tolls_amount                               0
improvement_surcharge                    0.3
total_amount                             5.8
M                                        151
X                                        310
B                                        260
Q                                        433
S                                        241
Name: 0, dtype: object

In [206]:
from sklearn.externals import joblib
filename = 'df.sav'
joblib.dump(df, filename)

['df.sav']

In [8]:
# load the model from disk
import numpy as np
filename = 'taxi_face_model.sav'
loaded_model = joblib.load(filename)
inputsec = np.array([3600]).reshape(-1, 1)
#inputsec = [3600].reshape(-1, 1)

result = loaded_model.predict(inputsec)
print(result)
print(result[0])

[16.97209416]
16.972094162292635

/anaconda3/lib/python3.6/site-packages/sklearn/base.py:251: UserWarning: Trying to unpickle estimator LinearRegression from version 0.20.1 when using version 0.20.2. This might lead to breaking code or invalid results. Use at your own risk.
  UserWarning)